### ISSUE TITLE
page migrating (legacy resin) base images appears to be missing

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [balena-io/docs#1008]
When I browse to:
https://www.balena.io/docs/reference/base-images/legacy-base-images/
The warning at the top says:

Warning: All resin/... base images are DEPRECATED in favor of the newer set of images under the 
namespace balenalib. For information on migrating to these new images checkout "Migrating to 
balenalib base images"

Unfortunately the page "migrating to balenalib base images" doesn't appear to exist in the repository. Clicking on the link reloads the page.

**Comment by shaunmulligan** [comment]
This was fixed and now directs the users down to the ["major changes"](https://www.balena.io/docs/reference/base-images/base-images/#major-changes) section of the base images doc which describes installing initsystem, etc. So I think this is closed for now.
