### ISSUE TITLE
Docs should clearly elucidate the difference between prod and dev images

### ISSUE THREAD

**Issue by xginn8** [balena-io/docs#1016]
Specifically, I find this wording to be rather confusing (taken from https://www.balena.io/docs/reference/OS/overview/2.x/#dev-vs-prod-images):

> 
>     Passwordless SSH into balenaOS on port 22222 as the root user.
>     Docker socket exposed on via port 2377, which allows balena local push to do remote Docker builds on the target device.
> 
> **The production images have all of the above functionality disabled by default**

To me this implies that ssh & a docker socket are generally disabled in prod, but what we mean specifically is that **passwordless** ssh is disabled, and an **exposed** docker socket is disabled.

**Comment by pdcastro** [comment]
The port number 2377, is it even correct? I thought it was 2375. I've definitely been using 2375... Maybe I'm missing out on 2377 features. :-)

**Comment by garethtdavies** [comment]
This should be resolved by https://github.com/balena-io/docs/pull/1327. Please reopen if not.
