### ISSUE TITLE
Known Tested Modems: replace SIM7100E with SIM7600E

### ISSUE THREAD

**Issue by pdcastro** [balena-io/docs#1020]
* The docs mention we support the SIM7100E modem: https://www.balena.io/docs/reference/OS/network/2.x/#known-tested-modems-
* meta-balena doesn't mention the SIM7100E but the SIM7600E instead:
https://github.com/balena-os/meta-balena/blob/master/README.md#modems

@floion and @shaunmulligan have confirmed that _"meta-balena is correct, the SIM7100E is deprecated in favour of the 7600."_

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h0er)

**Comment by shaunmulligan** [comment]
closed by https://github.com/balena-io/docs/pull/1072
