### ISSUE TITLE
Update CLI install instructions under os/docs/ pages

### ISSUE THREAD

**Issue by pdcastro** [balena-io/docs#1022]
Comparing the "balenaOS getting started" pages with the "balenaCloud getting started pages":

* https://www.balena.io/os/docs/intel-nuc/getting-started/
* https://www.balena.io/docs/learn/getting-started/intel-nuc/nodejs/

... we see that the balenaOS pages contain outdated installation instructions for the balena CLI:

* Outdated, balenaOS: https://www.balena.io/os/docs/intel-nuc/getting-started/#Install-the-Balena-CLI
* Current, CLI reference: https://www.balena.io/docs/reference/cli/#install-the-cli

This is of course confusing to balena users and led to the linked support request.

The easiest (best?) fix would be for the balenaOS instructions to simply point to (link to) the "CLI reference" instructions page.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h2a3)

**Comment by garethtdavies** [comment]
Looks like this was closed via https://github.com/balena-io/resin-site/commit/567a9dfa347c45b2bd935f86d482b396d69b4db2#diff-a8640baaa5927e523389a481ee18406fR21
