### ISSUE TITLE
$names.domain shouldn't contain www

### ISSUE THREAD

**Issue by dansku** [balena-io/docs#1026]
There is a variable `$names.domain` = `www.balena.io`, but this creates many link errors, redirecting to forums as https://forums.www.balena.io/c/troubleshooting [here](https://www.balena.io/docs/learn/getting-started/fincm3/python/).

Changing to balena.io would fix this issue.

**Comment by dimitrisnl** [comment]
I don't believe this is the best approach.

We would then rely on the redirects. Instead, we should fix the links in the first place.

```
// from
* If you still aren't able to get your device online, reach out to us in the [forums](https://forums.{{ $names.domain }}/).

// to
* If you still aren't able to get your device online, reach out to us in the [forums]({{ $names.domain }}/forums).
```

And maybe use the `HTTPS://` prefix for the domain itself.
