### ISSUE TITLE
Ensure that balenalib base images examples for init system show how to properly mount /dev as devtmpfs

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#1032]
Our current examples do not take into account mounting /dev as devtmpfs!

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hcnf)

**Comment by nghiant2710** [comment]
Fixed in https://github.com/balena-io-library/base-images/pull/526
