### ISSUE TITLE
Getting started guide showing markdown/syntax instead of links

### ISSUE THREAD

**Issue by tdicola** [balena-io/docs#1040]
I noticed the getting started guide here: https://www.balena.io/docs/learn/getting-started/raspberrypi3/nodejs/ Seems to be rendering some markdown or other markup syntax improperly, notice the 'What you will need' section looks like:
<img width="987" alt="screen shot 2019-03-08 at 9 04 24 am" src="https://user-images.githubusercontent.com/1332183/54043350-365a8780-4181-11e9-8701-95606284af24.png">
Likely the [rpi3B+] etc. tags should be turning those bits into links that go to other pages.

**Comment by lurch** [comment]
Looks like it's **all** combinations of boards and projects that have a broken 'What you will need section' e.g. https://www.balena.io/docs/learn/getting-started/fincm3/python/ also renders that part of the page incorrectly.

**Comment by lurch** [comment]
On a side-note, I just noticed that the balenaFin link on https://www.balena.io/docs/learn/getting-started/fincm3/python/ leads to https://store.resin.io/collections/balena-fin-home-page/products/fin-8gb which gives a 404 :slightly_frowning_face:

**Comment by sradevski** [comment]
@lurch Thanks for the report, I will open a new issue to handle that.
