### ISSUE TITLE
Python SDK Application docs incorrectly list `git_repository` as a returned field

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io/docs#1041]
As of v5 API/v7 SDK the git_repository field has been replaced with the slug field, the docs should be updated accordingly.

This has been updated in the Python SDK repo ( https://github.com/balena-io/balena-sdk-python/pull/129 ) so this repo just needs to be updated now.

**Comment by xginn8** [comment]
This has since been fixed.
