### ISSUE TITLE
Document that `balena sync` doesn't work with multicontainer (and is not recommended anymore)

### ISSUE THREAD

**Issue by pcarranzav** [balena-io/docs#1043]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hx9n)

**Comment by shaunmulligan** [comment]
@pcarranzav this needs to be done on the cli doc, since that is the only reference to`balena sync` that i can find
