### ISSUE TITLE
API endpoint with "\$" not being properly encoded on bash.

### ISSUE THREAD

**Issue by dansku** [balena-io/docs#1051]
User reported an issue on https://www.balena.io/docs/reference/api/resources/device_config_variable/ where if you run `curl` on `"https://api.balena-cloud.com/v4/device_config_variable?\$filter=device%20eq%20<DEVICE ID>"  the backslash and dollar sign does not get encoded properly, resulting in an error.

Forum post for the issue:
https://forums.balena.io/t/balena-api-calls-fail-with-database-error/5677

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_i5nv)

**Comment by Page-** [comment]
The issue was actually that a device uuid was being used where a device id was necessary, escaping the `\` just meant that the key stopped being `$filter` and became `\$filter` which doesn't do any filtering (and hence doesn't hit the issue with regards to id vs uuid)
