### ISSUE TITLE
"Advanced OS configuration" doc suggestions

### ISSUE THREAD

**Issue by lurch** [balena-io/docs#1056]
I was just looking at https://www.balena.io/docs/reference/OS/advanced/#raspberry-pi and saw that it mentions `gpu_mem`, `gpu_mem_256` and `gpu_mem_512` - I guess you might want to include `gpu_mem_1024` too? See https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md

It also says "gpu_mem_512 is used by the 512MB Raspberry Pi (Model B/B+ - this is probably what you have.)" - is it now more likely that people _probably_ have a 3B/3B+ with 1024MB of memory?

And finally it links at the bottom to http://elinux.org/RPiconfig which hasn't been updated since May 2016 - it might be better to link to https://www.raspberrypi.org/documentation/configuration/config-txt/ instead which I think is more regularly updated.

**Comment by dtischler** [comment]
This was actually fixed a while back, in https://github.com/balena-io/docs/commit/9bc4e8206b69f6fa15193b8afded472a7fe905bd.  Closing issue out now.
