### ISSUE TITLE
A URL with query params redirects to 404

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io/docs#1073]
Check this one [https://balena.io/docs?_ga=000](https://balena.io/docs?_ga=000)

**Comment by dimitrisnl** [comment]
In the following line, is where I believe we should allow for URL params. The fact that it's using RegEx is a bit problematic.

https://github.com/balena-io/docs/blob/8ce86158d49c039a5ec6525d9d7f6b6a72932b71/config/redirects.txt#L10

**Comment by dimitrisnl** [comment]
wondering if @shaunmulligan has any idea and I'm missing something

**Comment by vipulgupta2048** [comment]
Fixed with #1571
