### ISSUE TITLE
Raspberry Pi Zero W missing from the list of the devices when "Adding  new..."

### ISSUE THREAD

**Issue by joefernwright** [balena-io/docs#1111]
When someone wants to add a new device, to an application, in my case Raspberry Pi Zero W, it is missing from Device list. There are Raspberry Pi 2 and 3 available but Zero W is missing from the list.

Despite this, there is an Balena OS available for download (an image) for Raspberry Pi Zero but no instruction how to add flashed with it device to an application.

**Comment by vschinazi** [comment]
Hi

It would be really great if you could add the Pi Zero W to the device list. 
If not, can you please give instructions on how enable Wifi and how to add the flashed device to an existing application. 

Thank you.

**Comment by lurch** [comment]
> There are Raspberry Pi 2 and 3 available but Zero W is missing from the list.

This is just a random guess, but did you create a `armv7hf` application instead of a `rpi` application?
https://www.balena.io/docs/reference/base-images/devicetypes/

**Comment by vschinazi** [comment]
Hi, Thanks for the reply. No, I was looking to add a Pi Zero W device but it is not on the list. Can add a device as Pi 2 or Pi 3 and still use my Pi Zero? Will that work? Otherwise, I suspect that the best thing to do is to download the Balena OS for Pi Zero and then edit the wifi settings, right? 
Sorry, I am very new to all of this.
thank you.

**Comment by vschinazi** [comment]
Thank. So how do I add a Pi Zero W device if it is not on the device list?
![device_capture](https://user-images.githubusercontent.com/2072586/66737855-5a93ea80-ee6d-11e9-8b17-24544702fa78.PNG)

**Comment by vschinazi** [comment]
Solved it. I just needed to create another application ad the Pi Zero was listed. It was not in the previous list since my default application was set up for a Pi 3.
Thank you for all your help!
