### ISSUE TITLE
Remove `resin` references in balenaOS component image

### ISSUE THREAD

**Issue by xginn8** [balena-io/docs#1113]
Visible [here](https://www.balena.io/docs/reference/OS/overview/2.x/#balenaos-components), and fully resolvable [here](https://www.balena.io/docs/img/common/resinos/resinOS-components.png), these references should be updated to reflect the name change.

**Comment by lurch** [comment]
On a related note, I just noticed that one of the screnshots at https://www.balena.io/docs/learn/getting-started/raspberry-pi/nodejs/#adding-your-first-device (specifically https://www.balena.io/docs/img/raspberry-pi/os-options.png ) still mentions RESINOS.
The same problem seems to affect multiple other board-types too, e.g. https://www.balena.io/docs/img/orangepi-plus2/os-options.png

**Comment by lurch** [comment]
Hmmm, images on https://www.balena.io/docs/reference/OS/updates/self-service/ are affected too :eyes:

**Comment by garethtdavies** [comment]
The original issue was closed via https://github.com/balena-io/docs/pull/1332

Self-service image updates noted above are bundled into the ESR PR https://github.com/balena-io/docs/pull/1240 which has been stuck for a few months so I'll pull those out to fully resolve all comments above.

**Comment by garethtdavies** [comment]
Closing this via #1347
