### ISSUE TITLE
Clarify whitelisted domains subtlety in networking requirements

### ISSUE THREAD

**Issue by xginn8** [balena-io/docs#1122]
The documentation currently states that only three domains must be whitelisted, but by default NTP & DNS default to domains outside that whitelist (`*.resinio.pool.ntp.org` & `8.8.8.8`). I _think_ the intent is for these domains to fall under this category: "outward only (and inward once outward connection established)", though that is not entirely clear from context.

**Comment by pdcastro** [comment]
> [pdcastro] This issue has attached support thread https://jel.ly.fish/#/support-thread~fe9f29fc-9fda-4589-856a-eee45e505074

It seems that `*.s3.amazonaws.com` also needs to be whitelisted, as found in the support thread linked above.
