### ISSUE TITLE
Expand docs on enabling support access

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#1127]
currently we only have https://www.balena.io/docs/learn/manage/actions/#grant-support-access-to-application

We should expand on that explaining how to enable per app, per device and the implications of enabling it, linking to security docs.

**Comment by garethtdavies** [comment]
See https://www.flowdock.com/app/rulemotion/i-docs/threads/KpAPzGU06Ju1aTbq1peIG9UBRH7
