### ISSUE TITLE
cross-build-end / cross-build-start are no longer necessary

### ISSUE THREAD

**Issue by zvin** [balena-io/docs#1134]
See the example here https://www.balena.io/docs/reference/base-images/base-images/#building-arm-containers-on-x86-machines

`RUN [ "cross-build-start" ]`and `RUN [ "cross-build-end" ]` are no longer required and will fail on some base images like `balenalib/rpi-raspbian:latest`

**Comment by xginn8** [comment]
@zvin I've just tested cross-building an ARM container on my x86 laptop and it failed as expected with `standard_init_linux.go:211: exec user process caused "exec format error"`, which makes me think the `RUN ["cross-build-X"]` steps are still required. Am I missing something?

**Comment by nghiant2710** [comment]
Closing in favor of https://github.com/balena-io/docs/pull/1483
