### ISSUE TITLE
Fix mixpanel error on the docs site

### ISSUE THREAD

**Issue by gelbal** [balena-io/docs#1146]
See this comment for the actual problem:
https://github.com/balena-io/docs/issues/1146#issuecomment-547342195

Original description is outdated.

-----

In order to do accurate cross-domain tracking, we need to append the Amplitude device ID value as a parameter to the links going to the dashboard. So in the dashboard, we could fetch this anonymous identifier and create alias of the balenaCloud username. This way we merge the anonymous events that happen in the docs website with the signed up user.

Right now the links in blog work like this.

**Comment by garethtdavies** [comment]
@gelbal is this issue still relevant given the move to Amplitude?

**Comment by gelbal** [comment]
Thanks for checking @garethtdavies. This issue is still relevant. I updated the original post to reference to Amplitude.

We are missing the linking between Docs and the dashboard so the events coming from Docs in an anonymous session are never linked to the events happening after balenaCloud login. 

@roman-mazur could point out to how we did the implementation in blog and marketing websites -- in case you'd like to tackle this issue,

**Comment by roman-mazur** [comment]
@gelbal I didn't see this issue open
I think it was addressed in #1183 unless you see some links that are not instrumented.

**Comment by gelbal** [comment]
@roman-mazur ah that's true, you are right. As I didn't remember that we implemented this, I was just checking it and I didn't see the IDs passed in urls. Now after reading your comment, I checked again and I see the following errors on console that prevents updating the URL sometimes:

```
TypeError: this.mixpanel.get_distinct_id is not a functionbundle.js:1:2092
    allDeviceIds https://unpkg.com/analytics-client@0.1.1/dist/bundle.js:1
    getDeviceIdsQueryString https://unpkg.com/analytics-client@0.1.1/dist/bundle.js:1
    <anonymous> https://www.balena.io/docs/learn/manage/account/#sign-up:2729
    je https://www.balena.io/docs/dist/main.js:24
    attr https://www.balena.io/docs/dist/main.js:24
    <anonymous> https://www.balena.io/docs/learn/manage/account/#sign-up:2728
    l https://www.balena.io/docs/dist/main.js:24
    fireWith https://www.balena.io/docs/dist/main.js:24
    i https://www.balena.io/docs/dist/main.js:24
    t https://www.balena.io/docs/dist/main.js:24
```

It seems like sometimes we make the call before mixpanel lib is loaded. It doesn't happen every time but I see it happening almost half of the time I try it,

**Comment by roman-mazur** [comment]
Indeed. Ok, I'll try to see if there is a quick fix soon.

**Comment by gelbal** [comment]
Hey @roman-mazur I'm closing this issue as it looks like obsolete since you migrated the tracker to Amplitude.
