### ISSUE TITLE
custom udev rules are described only on the README of meta-balena

### ISSUE THREAD

**Issue by dt-rush** [balena-io/docs#1149]
https://github.com/balena-os/meta-balena#udevrules

We ought to have a docs page for this

**Comment by garethtdavies** [comment]
Related to https://github.com/balena-io/docs/pull/1249

**Comment by garethtdavies** [comment]
Closed by https://github.com/balena-io/docs/pull/1249 this information is now available via https://www.balena.io/docs/reference/OS/configuration/
