### ISSUE TITLE
Supervisor HTTP API link broken

### ISSUE THREAD

**Issue by chrisys** [balena-io/docs#1154]
At the bottom of this page: https://www.balena.io/docs/learn/deploy/release-strategy/update-locking/

**Comment by xginn8** [comment]
that link appears to resolve to https://www.balena.io/docs/learn/deploy/release-strategy/update-locking/API.md, though it's somehow invalid: https://github.com/balena-io/docs/blame/master/pages/learn/deploy/release-strategy/update-locking.md#L83

**Comment by xginn8** [comment]
this file is actually generated from https://github.com/balena-io/balena-supervisor/blame/master/docs/update-locking.md#L83, so i am not sure how to properly templatize this variable between the supervisor docs and this repo

**Comment by garethtdavies** [comment]
The file is also renamed in `fetch-external.sh` https://github.com/balena-io/docs/blob/master/tools/fetch-external.sh#L23. I think the only reasonable way to manage this is through a redirect.

**Comment by garethtdavies** [comment]
This isn't actually fixed. I tested the redirect via https://www.balena.io/docs/learn/deploy/release-strategy/update-locking/API which works as expected but the link with the file extension doesn't https://www.balena.io/docs/learn/deploy/release-strategy/update-locking/API.md. 

Am seeing this incorrect redirect:

```
redirecting /docs/learn/deploy/release-strategy/update-locking/API.md -> /docs/docs/learn/deploy/release-strategy/update-locking/API
```
