### ISSUE TITLE
Fully document change from `systemd-timesyncd` to `chrony`

### ISSUE THREAD

**Issue by xginn8** [balena-io/docs#1155]
As noted in https://github.com/balena-io/docs/pull/867, as of v2.13 balenaOS moved from `systemd-timesyncd` to `chronyd` and that has yet to be documented. cc @ZubairLK @agherzan

**Comment by garethtdavies** [comment]
A version note for the change from `systemd-timesyncd` -> `chronyd` was added here https://github.com/balena-io/docs/pull/1284/commits.

**Comment by garethtdavies** [comment]
Closed via https://github.com/balena-io/docs/pull/1380
