### ISSUE TITLE
Staging site docs are indexed by Google

### ISSUE THREAD

**Issue by chrisys** [balena-io/docs#1161]
I noticed when using Google to search the docs that some results were coming from the staging site - we shouldn't let search engines index this for duplicate content reasons, but it could also be confusing to the reader if the docs on staging are different from those on prod and they find them in search results.

![62707052-9d0df680-b9e8-11e9-8cb6-44bbd54ff3da](https://user-images.githubusercontent.com/521698/62879786-d1a0eb80-bd23-11e9-9f55-6afebced1019.png)

This also applies to the marketing site: https://github.com/balena-io/resin-site/issues/877

**Comment by georgiats** [comment]
I've had the same issue, I have typed manual BalenaOS releases and got this page https://www.balena-staging.io/os/docs/raspberrypi3/getting-started/ 
<img width="928" alt="balena staging" src="https://user-images.githubusercontent.com/4034214/82450835-e16d0d80-9ab5-11ea-80f0-cf6d35075b01.png">

**Comment by iamsolankiamit** [comment]
@chrisys @georgiats it was discussed with @alexandrosm that we should let staging results be there. Not able to find the Thread for it now :/

**Comment by srlowe** [comment]
Normal practice is to use canonical links in these cases : https://en.wikipedia.org/wiki/Canonical_link_element

**Comment by vipulgupta2048** [comment]
@iamsolankiamit Any definitive reason as to why that was the case so the issue can be closed?

**Comment by vipulgupta2048** [comment]
It's 2023, and I confirm the deletion of the docs staging environment with our move to Cloudflare Page #2449
