### ISSUE TITLE
Document device-hopping with `ssh ssh.resindevice.io` / `hostvia` for user's use

### ISSUE THREAD

**Issue by dt-rush** [balena-io/docs#1167]
Accessing a device you own with a busted VPN connection through another device you own on the same network is pretty basic and empowering.

**Comment by garethtdavies** [comment]
I've linked to the device debugging masterclass in this PR https://github.com/balena-io/docs/pull/1338 which shows how to use this. This will also be incorporated in the docs proper (and hence searchable) once https://github.com/balena-io/docs/pull/1295 is complete.

**Comment by garethtdavies** [comment]
This is now covered here https://www.balena.io/docs/learn/more/masterclasses/device-debugging/#4-accessing-a-device-using-a-gateway-device
