### ISSUE TITLE
Autogenerated docs are automatically deployed, but not committed

### ISSUE THREAD

**Issue by xginn8** [balena-io/docs#1169]
When regenerating documentation, any docs that are generated from upstream are included, however they have already been deployed to the production docs. This causes confusion for users submitting PRs and undue work in reviewing changes.

**Comment by lurch** [comment]
I guess the only danger here, is if autogenerated docs _are_ committed, people might submit PRs against the autogenerated docs, not realising that they're editing "output files" and not "input files" ? :man_shrugging:

**Comment by xginn8** [comment]
@lurch this is actually already true, and often a source of confusion for people trying to contribute! I myself am often a victim as well

**Comment by garethtdavies** [comment]
I'm going to close this (please re-open if you feel differently) but as external docs have been removed from the repo they can't be committed. There is a related but different issue with regards to ensuring that the docs are published from an upstream documentation change (there is currently no trigger to force a rebuild) but I'll record that separately.
