### ISSUE TITLE
Update docs to reflect we are not using systemd in base images

### ISSUE THREAD

**Issue by nazrhom** [balena-io/docs#1181]
While we do mention this in the base images page, there are other places in the docs where we could be more explicit about what the default is. For example https://www.balena.io/docs/learn/develop/runtime/#mounting-external-storage-media could clarify that if you are running the newer base images, you probably don't have systemd enabled unless you activated it manually (And link to https://www.balena.io/docs/reference/base-images/base-images/#installing-your-own-initsystem)

**Comment by garethtdavies** [comment]
There have been a few updates removing [INITSYSTEM references](https://github.com/balena-io/docs/issues/1106) and [systemd](https://github.com/balena-io/docs/issues/1262). I've done a search for remaining systemd references and they all look relevant so closing this.
