### ISSUE TITLE
Update image partition layout 

### ISSUE THREAD

**Issue by garethtdavies** [balena-io/docs#1213]
https://www.balena.io/os/docs/architecture/#Image-Partition-Layout is outdated and the layout is actually https://github.com/balena-os/meta-balena/blob/development/meta-balena-common/classes/image_types_resin.bbclass#L26

**Comment by lurch** [comment]
Also, the text on that page says 'resin-state' but the images say 'resin-conf'.

**Comment by lurch** [comment]
Closed by #1333 ?

**Comment by garethtdavies** [comment]
Thanks @lurch but not quite as I need to copy this all over to the balena.io/os site (which is what this issue originally referenced). I just need to update the last bit of https://www.balena.io/docs/reference/OS/overview/2.x regarding Yocto and then I'll push all the changes over and close this.

**Comment by lurch** [comment]
Ahhh, I didn't spot the `/os/` part of the original URL :wink: 
Rather than having the docs manually copied from one site (and/or repo?) to the other, is this another place where your "copy external docs into this repo" script could come in useful?

**Comment by garethtdavies** [comment]
That would be ideal but that's not currently possible in the same way as the others have been implemented (e.g. the /os/ site is private). Agree though copying from one to the other isn't a good long term solution so hopefully will resolve this sooner rather than later.

**Comment by garethtdavies** [comment]
This will be closed via https://github.com/balena-io/resin-site/pull/954
