### ISSUE TITLE
NetworkManager connectivity settings from meta-balena repo

### ISSUE THREAD

**Issue by robertgzr** [balena-io/docs#1220]
Our docs for NetworkManger on devices running balenaOS v2.x don't include the meta-balena feature to check for connectivity.

\[1]: https://www.balena.io/docs/reference/OS/network/2.x/
\[2]: https://github.com/balena-os/meta-balena#connectivity

**Comment by xginn8** [comment]
Closed by https://github.com/balena-io/docs/pull/1251
