### ISSUE TITLE
Mention SSH key is required for `balena ssh`

### ISSUE THREAD

**Issue by chrisys** [balena-io/docs#1238]
I'll link a support ticket where it was not clear that the use of the `balena ssh` CLI command required that an SSH key be set up on the user's account. It doesn't mention that it's required here: https://www.balena.io/docs/learn/manage/ssh-access/#using-balena-ssh-from-the-cli

However it is mentioned here: https://github.com/balena-io/balena-cli/blob/master/INSTALL.md#configuring-ssh-keys

**Comment by garethtdavies** [comment]
I think the one caveat to this is you don't need an SSH key when accessing via SSH locally i.e. via  `UUID.local` or local IP `192.168.0.12` but when you are accessing the device via the balenaCloud VPN you do?
