### ISSUE TITLE
Template variables are not replaced in HTML output

### ISSUE THREAD

**Issue by garethtdavies** [balena-io/docs#1247]
Example: https://forums.balena.io/t/device-authentication/48664/2
Flowdock thread: https://www.flowdock.com/app/rulemotion/user_happiness/threads/Y-LLqOpWfIAOLtLWtFcGUGtiLtF

Some background info: https://meta.discourse.org/t/rich-link-previews-with-onebox/98088
Replicate via: https://iframely.com/embed/https%3A%2F%2Fwww.balena.io%2Fdocs%2Flearn%2Fwelcome%2Fsecurity%2F

**Comment by garethtdavies** [comment]
The issue is `{{ excerpt }}` is output but does not expand the variables see https://github.com/balena-io/docs/blob/master/templates/default.html#L12

**Comment by lurch** [comment]
Should that example https://forums.balena.io/t/device-authentication/48664/2 be working "properly" now that #1310 has been merged? :man_shrugging:

**Comment by garethtdavies** [comment]
I tested the link there and it displays correctly now i.e. https://iframely.com/embed/https%3A%2F%2Fwww.balena.io%2Fdocs%2Flearn%2Fwelcome%2Fsecurity%2F. I'm guessing there is caching on the forum, so probably little we can do about it.

**Comment by garethtdavies** [comment]
Just to confirm, I edited that post and so now it previews correctly.
