### ISSUE TITLE
Network requirements references `dnsServer` property instead of `dnsServers`

### ISSUE THREAD

**Issue by hedss** [balena-io/docs#1248]
At: https://www.balena.io/docs/reference/OS/network/2.x/#network-requirements
"To avoid any requests being made to 8.8.8.8 by balenaOS, modify the `dnsServer` setting in config.json."
Should read:
"To avoid any requests being made to 8.8.8.8 by balenaOS, modify the `dnsServers` setting in config.json."

**Comment by lurch** [comment]
...and clicking on the link there takes you to https://github.com/balena-os/meta-balena#dnsservers which says "without any additional servers servers.", which is probably a typo? :wink:

**Comment by garethtdavies** [comment]
Related to this I just added all the config.json content to this draft PR https://github.com/balena-io/docs/pull/1249
