### ISSUE TITLE
Balena SSH CLI Docs

### ISSUE THREAD

**Issue by dtischler** [balena-io/docs#1263]
Looking at this page:  https://www.balena.io/docs/learn/manage/ssh-access/#using-balena-ssh-from-the-cli

The default behavior of the balena ssh command has been modified slightly, and documentation needs to be updated to reflect this.  There is no need to add the '--host' or '-s' flags anymore, as the default action will take you into the HostOS.  All that is needed to SSH to the host now is thus "balena ssh <device-uuid>".

In order to SSH into a container, that would be "balena ssh <device-uuid> <container-name>"

**Comment by garethtdavies** [comment]
There is also this PR #1239
