### ISSUE TITLE
wording patch to dbus hostname change warning

### ISSUE THREAD

**Issue by dt-rush** [balena-io/docs#1271]
The wording in this doc in this part is not clear:

> Changing the device hostname is no longer possible via this method, due to the fact that the /etc/hostname file is stored on the read-only root partition. To change the device hostname, use the [balena supervisor API](https://www.balena.io/docs/reference/supervisor/supervisor-api/#patch-v1-device-host-config).

Ought to be made more clear:

> Changing the device hostname via a dbus-send method invocation of `org.freedesktop.hostname1.SetHostname` is no longer possible, due to the fact that this would attempt to write to `/etc/hostname`, which on the host OS is stored in the read-only root partition. To change the device hostname, use the [balena supervisor API](https://www.balena.io/docs/reference/supervisor/supervisor-api/#patch-v1-device-host-config).

**Comment by garethtdavies** [comment]
This was merged so closing.
