### ISSUE TITLE
Suggested wifi dongle is discontinued

### ISSUE THREAD

**Issue by xginn8** [balena-io/docs#1277]
[Adafruit Miniature Wifi (802.11B/G/N) Module](https://www.adafruit.com/product/814) on https://www.balena.io/docs/reference/hardware/wifi-dongles/ is now marked as discontinued.

**Comment by lurch** [comment]
The official Raspberry Pi Wifi dongle (also linked to by that page) is discontinued too.

I wonder if it would be worth adding a list of which of the SBCs supported by Balena 
have built-in Wifi, and so don't need a dongle? :man_shrugging:

**Comment by lurch** [comment]
Haha, see also #602

**Comment by garethtdavies** [comment]
I guess we should update this to just be this https://github.com/balena-os/meta-balena#wifi-adapters (albeit that example one is discontinued)
