### ISSUE TITLE
Update "Going to production" docs to include a link to the CLI Advanced Masterclass

### ISSUE THREAD

**Issue by pdcastro** [balena-io/docs#1281]
Specifically / especially in the section "Preloading images" -
https://www.balena.io/docs/learn/welcome/production-plan/#preloading-images

... currently the documentation includes a ***broken*** link (broken page anchor) to the CLI's [preload command reference](https://www.balena.io/docs/reference/cli/#preload-image), but now that the CLI Advanced Masterclass exists, I think the link should be updated (including maybe a couple of introductory sentences) to refer to Section 5: Preloading and Preregistering of the masterclass:
https://github.com/balena-io-projects/balena-cli-advanced-masterclass#5-preloading-and-preregistering

The section title "Preloading images" could also be amended to "Preloading images and pre-registering devices", as device pre-registration is also a relevant "going to production" topic.

And, it goes without saying (or in case it doesn't), :-) this Github issue is just an improvement thought / suggestion, please exercise judgment and don't assume I know better. :-)

**Comment by garethtdavies** [comment]
👍 to including additional links to the masterclasses. I've been trying to surface more of this content directly and then linking to the masterclasses for more detail. 

There is a planned revamp of this section https://www.flowdock.com/app/rulemotion/resin-propaganda/threads/v3Iv8-q9bNyU9lqaoXdvxNBwqHJ so I've made the minimal changes to include the extra information in this associated PR.
