### ISSUE TITLE
Device data collected by the supervisor: Should remove the "(if allowed)" part

### ISSUE THREAD

**Issue by thgreasi** [balena-io/docs#1286]
In the Collected Data page we mention:
> Data is submitted to Mixpanel from balena-managed devices (if allowed) on the events listed in the table below.

Since we do not offer a way to users to opt out their devices from sending analytics, we should remove the `(if allowed)` part from that sentence.

See: https://www.balena.io/docs/learn/more/collected-data/

**Comment by garethtdavies** [comment]
I would guess this wording is included as it can be disabled via `config.json`?  Perhaps _unless disabled_ or somesuch would likely be better terminology than _if allowed_?

Worth @gelbal or @roman-mazur chiming in here though.

**Comment by garethtdavies** [comment]
Sorry, I just found Flowdock thread https://www.flowdock.com/app/rulemotion/public-s-balenaos/threads/Mt4S1IeWPbiRCeg_N67eFIbVPoN as the JF link above is a 404. Working link is https://jel.ly.fish/6184d522-91cd-4986-be50-e9a32b65e8c4
