### ISSUE TITLE
Add Nvidia Jetson Xavier to devices

### ISSUE THREAD

**Issue by garethtdavies** [balena-io/docs#1304]
More discussion here: https://www.flowdock.com/app/rulemotion/resin-propaganda/threads/eCp9GZKZfMb7YU6XeqQlRT7CUFl

**Comment by alisondavis17** [comment]
@vipulgupta2048 I think this exists already and thus the issue can be closed - see https://www.balena.io/docs/learn/getting-started/jetson-xavier/nodejs/
