### ISSUE TITLE
Links to available tags for base image builds broken

### ISSUE THREAD

**Issue by hardillb** [balena-io/docs#1309]
e.g. the link at the end of the second row of this table:

https://www.balena.io/docs/reference/base-images/base-images-ref/#RaspberryPi

Should be:

https://registry.hub.docker.com/r/balenalib/raspberrypi3-node/tags

not 

https://registry.hub.docker.com/u/balenalib/raspberrypi3-node/tags/manage/

Looks like all the similar links on the page need fixing.

**Comment by lurch** [comment]
Looks like that page was last modified in #1064 
Something else to autogenerate, @garethtdavies ? :wink:

**Comment by lurch** [comment]
Looks like the DockerHub links in the middle column also need to have the `/u/` in the middle changed to `/r/` ?

**Comment by garethtdavies** [comment]
Thanks for reporting and I've updated this. Note this is the same content as is on https://github.com/balena-io-library/base-images/blob/master/docs/balenalib-base-images-reference.md (I'll make a PR there too) but in the future it makes more sense to keep the latter updated and the docs pull this info from there.
