### ISSUE TITLE
Intel Edison + dfu-util on OSX 10.11.1 (El Capitan)

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#132]
Currently there is a known issue where dfu-util will not be able to burn OS images onto the intel edison when run on OSX 10.11.1

**Comment by zwalchuk** [comment]
don't know if this is still an issue, need to investigate

**Comment by shaunmulligan** [comment]
I think this can be closed for now, not many new deployments happening with Edison since it got EoL'd
