### ISSUE TITLE
Persistent storage has a broken link

### ISSUE THREAD

**Issue by anujdeshpande** [balena-io/docs#1331]
https://github.com/balena-io/docs/blob/master/shared/general/persistent-storage.md has a broken link with the named values

**Comment by garethtdavies** [comment]
Hi @anujdeshpande, the link to this page is here https://www.balena.io/docs/learn/develop/runtime/#persistent-storage and I think the link is working correctly. It appears in this instance it is a "partial" so we can reuse this text in multiple places and it is referencing another anchor on the page in which it is embedded. While in this instance, this doesn't really need to be a partial, the docs aren't really designed to be read directly from GitHub e.g. the variable names will not be expanded so I imagine anywhere we have used links of the form `{{ $links.githubMain }}` will also not work correctly on GitHub.

**Comment by lurch** [comment]
@garethtdavies Maybe it'd be worth adding something to https://github.com/balena-io/docs/blob/master/README.md explaining that some of the pages may not work correctly when viewed on GitHub, and should instead be viewed via https://www.balena.io/docs/ ? :man_shrugging:
