### ISSUE TITLE
contracts: Leading dash for optional services causes build failure

### ISSUE THREAD

**Issue by acostach** [balena-io/docs#1341]
The leading dash in the contracts doc for optional containers causes build failure:
```
labels:
      - io.balena.features.optional: 1
```

Failure observed:
```
[Error]    Could not parse compose file
[Error]      data/services/tx2_28_3/labels should be object, data/services/tx2_28_3/labels/0 should be string, data/services/tx2_28_3/labels should match exactly one schema in oneOf
[Error]    Not deploying release.
```

Without the dash, like in the examples at https://www.balena.io/docs/reference/supervisor/docker-compose/#labels , the optional services build fine.

@CameronDiver can you please confirm if the second form, without the dash is the right one?

**Comment by garethtdavies** [comment]
That's strange. I went back and looked at my test app for this and I was indeed using:

```
    labels:
      - io.balena.features.optional=1
```

Not only that, but I pushed now and it works so I have no idea. It's YAML so is it being particular about the indentation that you've used? That being said, it should be consistent so this should be updated to match the layout of the labels.

**Comment by garethtdavies** [comment]
Just to close this (fix in the PR) but either form are acceptable but not the hybrid version that crept in 😕 

```
labels:
      - io.balena.features.optional=1
```

or

```
labels:
      io.balena.features.optional: '1'
```
