### ISSUE TITLE
Correct spacing in custom base images doc.

### ISSUE THREAD

**Issue by szony** [balena-io/docs#1352]
The doc is here
https://www.balena.io/docs/reference/base-images/custom-docker-base-images/

It needs a space added where it says "it bases from the Docker Hubimage"

It should say "it bases from the Docker Hub image"

**Comment by garethtdavies** [comment]
@szony I've never seen that page before :) Curious, how did you find it, as it isn't in the navigation and I can't find any references to it. On a quick scan, it seems pretty dated.

**Comment by szony** [comment]
@garethtdavies google is still indexing it, my search was:
balena base images site:balena.io

**Comment by garethtdavies** [comment]
Right, thanks. I'm going to remove that page as it is outdated and I presume as a result purposely hidden from the navigation which will close this issue. There is some more general info on that page which is worth capturing and there is this existing issue https://github.com/balena-io/docs/issues/454
