### ISSUE TITLE
Implement method for updating external sources on update

### ISSUE THREAD

**Issue by garethtdavies** [balena-io/docs#1354]
Currently, we have a number of external sources in [fetch-external.sh](https://github.com/balena-io/docs/blob/master/tools/fetch-external.sh). These are only updated when the docs are deployed and not on an upstream merge. Ideally, we'd trigger a docs build when upstream changes are merged into master e.g. using webhooks.

**Comment by vipulgupta2048** [comment]
Closing in favor of #1525 as the discussion is happening there.
