### ISSUE TITLE
Mention Jetson TX2 L4T 32.2 partition-set incompatibilities with previous 28.x releases

### ISSUE THREAD

**Issue by acostach** [balena-io/docs#1363]
Starting with BalenaOS 2.47. we upgraded to L4T 32.2, and trying to flash a board that was running L4T 28.x with a l4t 32.2 sd-card will result in failure. It's necessary to either perform hostOS update from dashboard or update the tegra partitions, for instance using the BSP archive. 

This happens because the new 32.2 kernel is incompatible with the nvidia emmc partitions from L4T 28.x. During HUP we re-create these partitions before re-booting, however, with sd-card it's not possible to replace them before kernel boots, because even u-boot is also at the previous l4t revision on the emmc.

**Comment by garethtdavies** [comment]
@acostach Any preference for where this note should be?

I would probably default to having it in troubleshooting and including in the appropriate getting started guide. Does it also need to be in the dashboard instructions or is being in the docs enough? 

Finally, just to confirm this only effects the TX2 and no other Nvidia boards (or they already running 32.2)?

**Comment by acostach** [comment]
@garethtdavies I think the troubleshooting section as you say is very good.

It's for TX2 only for now, will be for TX1 as well once we upgrade it too. The jetson-nano and xavier were released along with 32.X, so there was no 28 for them.

So we need to mention that the sd-card flash incompatibility is from 28.X to 32.2 and newer.

Thanks!
