### ISSUE TITLE
Document user management via API

### ISSUE THREAD

**Issue by szony** [balena-io/docs#1412]
It is possible to add/remove users via our API, however it's not documented. There are two end points where we seem to have users but there are no examples shown:
https://www.balena.io/docs/reference/api/resources/application/
https://www.balena.io/docs/reference/api/resources/user/

**Comment by garethtdavies** [comment]
Here is the [internal discussion](https://www.flowdock.com/app/rulemotion/r-beginners/threads/weRbDgP1owWWC_Tb4DqREuhyWn8) with additional examples to add.
