### ISSUE TITLE
Update application API endpoint examples to show commands only for user applications

### ISSUE THREAD

**Issue by garethtdavies** [balena-io/docs#1418]
Since the introduction of public apps, the `https://api.balena-cloud.com/v5/application` now returns 100 other public applications in addition to the user's apps.

You can limit this by passing in a filter `https://api.balena-cloud.com/v5/application?$filter=is_public eq false` or there is the `https://api.balena-cloud.com/v5/my_application` endpoint. It's likely that the latter is what most users would expect to be returned by default.

cc @szony who raised this

**Comment by szony** [comment]
@garethtdavies are we planning to mention this in our documentation?

**Comment by garethtdavies** [comment]
@szony yes I'm on it. I was missing all the context from internal FD conversation so added this issue as a placeholder as wasn't see if we'd see those messages again!
