### ISSUE TITLE
Rollback Documentation

### ISSUE THREAD

**Issue by dtischler** [balena-io/docs#1428]
Could we please include the content /material that is located here:  https://github.com/balena-os/meta-balena/blob/development/docs/rollbacks.md, somewhere in the Docs site?  Upon glancing, I suspect one logical location would be here:  https://www.balena.io/docs/reference/OS/updates/update-process/#what-happens-during-a-balena-host-os-update

Thanks!

**Comment by garethtdavies** [comment]
See this forum thread for more discussion https://forums.balena.io/t/balena-os-fallback-process/101018/3
