### ISSUE TITLE
Docs should fetch device type information dynamically

### ISSUE THREAD

**Issue by sradevski** [balena-io/docs#1442]
Currently we have a `device-types.json` file that is the source of truth for the getting started guide. This is quite error-prone and it needs to be manually updated, so we need to change it to fetch the device types info dynamically.

**Comment by cywang117** [comment]
@vipulgupta2048 I believe this issue is already taken care of, see https://github.com/balena-io/docs/blob/master/templates/_devices.html where there is a dynamic query on page load which queries device types from balenaAPI.

Can I close this issue?

**Comment by cywang117** [comment]
@vipulgupta2048 Yeah this issue is definitely not solved -- it's referring to https://github.com/balena-io/docs/blame/master/config/dictionaries/device.json

**Comment by vipulgupta2048** [comment]
Yeap, we will remove this soon enough once Contracts can get provisioning instructions sorted.

**Comment by vipulgupta2048** [comment]
It finally did with the PR I merged here: https://github.com/balena-io/balena-sdk/pull/1101
And, it's coming into effect with #2613
