### ISSUE TITLE
Broken link to external docs (`nm-settings`)

### ISSUE THREAD

**Issue by wrboyce** [balena-io/docs#1478]
On https://www.balena.io/docs/reference/OS/network/2.x/#wifi-setup, the URL to https://developer.gnome.org/NetworkManager/stable/nm-settings.html is no longer valid (404).

It looks like that page was just a html copy of man 5 nm-settings which is mirrored in a few places such as https://manpages.debian.org/testing/network-manager/nm-settings.5.en.html

**Comment by szony** [comment]
Looks like our reference in another place is broken too. On https://www.balena.io/docs/reference/OS/network/2.x/ there's invalid link to https://developer.gnome.org/NetworkManager/stable/nm-settings.html

The url @wrboyce refers to only lists general connection options, the full reference can be found here:
https://developer.gnome.org/NetworkManager/stable/ref-settings.html

**Comment by mpous** [comment]
The link pointing to the same place on https://www.balena.io/docs/reference/OS/network/2.x/#introduction is also broken (probably the same that Daniel pointed).

**Comment by klutchell** [comment]
Fixed in https://github.com/balena-io/docs/pull/1522
