### ISSUE TITLE
Add more device configuration values

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/docs#1489]
In the [variable list](https://www.balena.io/docs/learn/manage/configuration/#variable-list) used for device configuring, we show a table of keys, values, descriptions, and required OS. This table should be revisited and updated with any new values.

For example, the Supervisor now supports configuring [FDT](https://github.com/balena-io/balena-supervisor/pull/1371) and [ODMDATA](https://github.com/balena-io/balena-supervisor/pull/1436)

The values in this table appear to be for all devices and a section just below it shows device specific configurations such as Config.txt on the Raspberry Pi device. We should add device specific configurations for the TX2 device line since it now has support for ODMDATA and FDT as linked above.

note: As of writing this issue the features are merged into Supervisor master but not in production yet so this issue will need to wait until that.

**Comment by acostach** [comment]
This values are in production, so they need be documented. The variables are in this form:
```
"RESIN_HOST_EXTLINUX_fdt": "custom.dtb"
"RESIN_HOST_ODMDATA_configuration": "6"
```

**Comment by 20k-ultra** [comment]
closing in favor of https://github.com/balena-io/docs/issues/1601

**Comment by 20k-ultra** [comment]
sorry, I thought this issue was created in another repo.

**Comment by 20k-ultra** [comment]
The Supervisor wants to document all these vars with https://github.com/balena-os/balena-supervisor/issues/1646 and then https://github.com/balena-io/docs/issues/1808 will pull that into this repository and in the final doc build.
