### ISSUE TITLE
Transfer Application Ownership should describe how the devices or services are affected

### ISSUE THREAD

**Issue by codewithcheese** [balena-io/docs#1503]
[Transfer Application Ownership](
https://www.balena.io/docs/learn/manage/actions/#transfer-application-ownership) does not describe if there is any affect on the devices during transfer. 

~~According to @richbayliss the services will be stopped and re-downloaded.~~
According to Shaun, (probably) nothing changes on the state endpoint, so containers/services would be neither re-downloaded nor stopped. Check the thread:
https://www.flowdock.com/app/rulemotion/public-s-community/threads/SOhsydbNmDge_Cb6AR0pzrlDR5X

**Comment by joehounsham** [comment]
Nothing changes on the application side or on the device e.g containers restarting, during the application transfer process, apart from the application owner. I'll create a new PR that clarifies this and some other points on the application transfer process.
