### ISSUE TITLE
Getting started guides needed for devices

### ISSUE THREAD

**Issue by acostach** [balena-io/docs#1539]
https://docs.resin.io/nitrogen8mm-sbc/nodejs/getting-started/#adding-your-first-device -> https://boundarydevices.com/product/nitrogen8m-mini/ uses sd-card for flashing as mentioned in instructions

https://docs.balena.io/jetson-xavier-nx-devkit-sd-card/nodejs/getting-started/#adding-your-first-device -> https://developer.nvidia.com/embedded/jetson-xavier-nx-devkit uses sd-card for flashing as mentioned in instructions

https://docs.balena.io/jetson-xavier-nx-devkit-emmc/nodejs/getting-started/#adding-your-first-device -> https://developer.nvidia.com/embedded/jetson-xavier-nx uses jetson-flash for flashing as mentioned in instructions

http://docs.resin.io/imx8m-var-dart/getting-started/#adding-your-first-device -> https://shop.variscite.com/product/evaluation-kit/dart-mx8m-evaluation-kits/#_ga=2.226744669.1773822250.1607418338-1994371556.1599813799&_gac=1.83905259.1607418338.Cj0KCQiA5bz-BRD-ARIsABjT4ngl0O6yzgsxteCRTZZ22sGiw6dpbp0Bj4mAIvB-oaiJyC6AqeIJ6xwaAsn-EALw_wcB#utm_source=https://www.google.com/#utm_medium=N/A#utm_campaign=N/A#utm_content=N/A#utm_term=N/A uses sd-card for flashing as mentioned in instructions

http://docs.resin.io/imx8mm-var-dart/getting-started/#adding-your-first-device -> https://shop.variscite.com/product/evaluation-kit/dart-mx8m-mini-evaluation-kits/#_ga=2.4914803.1773822250.1607418338-1994371556.1599813799&_gac=1.251493620.1607418426.Cj0KCQiA5bz-BRD-ARIsABjT4ni3PPzxBT_Ypdo8a_ItzN77bWUJs8Q4_WlAQteaAVdASwQ8ILX5dNgaAoZ3EALw_wcB#utm_source=https://www.google.com/#utm_medium=N/A#utm_campaign=N/A#utm_content=N/A#utm_term=N/A uses sd-card for flashing as mentioned in instructions

https://docs.balena.io/nsnopc-t4/nodejs/getting-started/#adding-your-first-device -> https://www.friendlyarm.com/index.php?route=product/product&product_id=225 uses sd-card for flashing as mentioned in instructions

https://docs.resin.io/jetson-nano-emmc/nodejs/getting-started/#adding-your-first-device -> https://developer.nvidia.com/embedded/jetson-nano uses jetson-flash for flashing as mentioned in instructions

**Comment by vipulgupta2048** [comment]
Getting Started guide needed for `Jetson Nano EMMC` device. 
Related issue: https://jel.ly.fish/de14c712-647c-4a9e-bf86-d44bd926fc94

**Comment by vipulgupta2048** [comment]
Add Getting Started guide for each device in a separate PR for easier reviews.

**Comment by vipulgupta2048** [comment]
I am thinking to break down this issue fully into individual pieces. Will create many issues from so more folks are able to pick these up in the release party. @acostach Can you check if there are any more devices we are missing? Open a issue for each one that we are missing so folks can pick it up and solve that.
