### ISSUE TITLE
Update device statuses

### ISSUE THREAD

**Issue by xginn8** [balena-io/docs#1543]
https://www.balena.io/docs/learn/manage/device-statuses/ is out of date and not yet updated to the combined statuses we now use.

**Comment by karaxuna** [comment]
@thgreasi I see that combined statuses are also explained in docs. Shall we close this?

**Comment by thgreasi** [comment]
I don't think the docs have been updated yet @karaxuna . I still see the separate vpn-heartbeat status icons.
![image](https://user-images.githubusercontent.com/1295829/111784910-9cc42580-88c4-11eb-9e72-ca839f5b51ac.png)

**Comment by vipulgupta2048** [comment]
This issue required more investigation and context, hence moved it to intermediate.
