### ISSUE TITLE
Update Organization Screenshots and Instructions

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-io/docs#1547]
Screenshots in Organization documentation needs to be of the original blue header color that is applied by default in balenaCloud to maintain consistency with other screenshots on the website. 

RGB color of header is 35, 68, 94

**Comment by gantonayde** [comment]
Can you show or link to an example?

**Comment by andrewnhem** [comment]
I think this one is a bit more severe than first issued. After 16 Dec, the team updated the balenaCloud UI, changing the way people navigate and steps taken. We'll want to update the screens and instructions.

**Comment by andrewnhem** [comment]
resolved with https://github.com/balena-io/docs/pull/1683
