### ISSUE TITLE
Will need getting started for Raspberrypi 400

### ISSUE THREAD

**Issue by acostach** [balena-io/docs#1548]
Pi400 is a non flasher type, and is provisioned identically as the Raspberrypi 4

link in device provisioning modal: 
linux: 'https://www.balena.io/docs/learn/getting-started/raspberrypi400/nodejs/'

Device: https://www.raspberrypi.org/products/raspberry-pi-400/

**Comment by lurch** [comment]
...and also for the CM4? https://www.raspberrypi.org/products/compute-module-4/
