### ISSUE TITLE
document custom boot splash screen

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#155]
Customizing splash

We configure all of our initial images to produce a resin logo at boot, shutdown or reboot. But we encourage any user to go and replace that logo with their own. All you have to do is replace the splash/resin-logo.png file that you will find in the first partition of our images (boot partition) with your own image. NOTE: As it currently stands plymouth expects the image to be named resin-logo.png.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_kj2)

**Comment by shaunmulligan** [comment]
Need to probably add this to FAQs as well

**Comment by Seungja** [comment]
Even if you do it that way, whenever you update your code the device loads the resin logo again isn't it?

**Comment by shaunmulligan** [comment]
@Seungja no, it should always load up whatever splash image you wrote over the resin-logo.png

**Comment by Seungja** [comment]
I must be doing something wrong then, i replace the **splash/resin-logo.png** then boot a **_Intel NUC_** with that image and the custom splash loads fine, but just after **Post Provisioning** _(when you must remove the USB drive and boot from disk)_ it loads default **Resin** Splash from there onwards. 😞

**Comment by shaunmulligan** [comment]
@Seungja ahh... I know what is going on. The issue is that this feature was broken on the flasher types (where resinOS is written to the internal storage, as in the case of the NUC) We have fixed that, but it has yet to be deployed on the intel NUC images. You can see the change log here: https://github.com/resin-os/meta-resin/blob/master/CHANGELOG.md#v19---2016-08-24

Hopefully in the next week or so we can get the latest version up on resin.io

**Comment by Seungja** [comment]
@shaunmulligan Thanks for the info!, i'll have to wait for the version change then 😃

**Comment by shaunmulligan** [comment]
hey @Seungja , I believe that resinOS 2.0.4 is now available in production for the intel nuc. So in theory this feature should work for you. Let me know how the testing goes. 
Cheers
Shaun

**Comment by Seungja** [comment]
Hello @shaunmulligan, i just made some tests with the **resinOS** 2.0.4 version. and sadly, the behavior is the same :(

I even tried making a new application and starting anew but still just after post provisioning the splash resets to the default one.

**Comment by shaunmulligan** [comment]
Hey @Seungja I spoke to one of the device engineers (@Telphan) and he said it might be a regression, so he is going to look into what is going on. It might also be worth raising an issue on http://github.com/resin-os/resinos as it will have better visibility and tracking for the team there.

**Comment by mathvav** [comment]
Is this still an issue? It looks like it may have already been resolved: https://github.com/balena-os/balena-os/issues/316

**Comment by lurch** [comment]
Looks like this _is_ documented at https://github.com/balena-io/docs/blob/master/shared/overview/2.x.md#dev-vs-prod-images but perhaps this issue is suggesting it should be documented more prominently? (see also #1307 )

**Comment by garethtdavies** [comment]
This is a _very_ old issue so likely those docs above didn't exist then. I also added in a reference via https://www.balena.io/docs/reference/OS/advanced/#disabling-rainbow-splash-screen so I think I'll close this for now as it'll return at least a couple results searching for splash.
