### ISSUE TITLE
Broken link on Getting Started page

### ISSUE THREAD

**Issue by kenna-smith** [balena-io/docs#1555]
There is a broken link in the Getting Started template.

To replicate:
1. go to this page: https://www.balena.io/docs/learn/getting-started/raspberrypi3/python/
2. notice that clicking on the link marked "Host OS" in the second paragraph results in a 404 error
3. notice that it appears to be broken in the template itself as well: https://github.com/balena-io/docs/blob/master/shared/getting-started/introduction/_default.md

I believe it is meant to link here: https://www.balena.io/docs/reference/OS/overview/2.x/

But I would like to verify that before fixing it. :)

**Comment by vipulgupta2048** [comment]
Good find @kenna-smith Thanks for identifying the 404, and a potential fix alongside it. From next time, you can just straight up make a PR. It's all good. I see the same link is broken in all templates of the introduction folder. 

In your PR fixing the link, please do correct the link in all the files listed here https://github.com/balena-io/docs/tree/master/shared/getting-started/introduction

Let us know if you need any help! :hatching_chick:

**Comment by vipulgupta2048** [comment]
hey @kenna-smith any updates?
