### ISSUE TITLE
Explain balena.yaml type field

### ISSUE THREAD

**Issue by Hades32** [balena-io/docs#1558]
I tried to find out, what the `type` field in the `balena.yaml` file meant and only got this:
https://www.balena.io/docs/learn/deploy/deploy-with-balena-button/#balenayml-configuration-file
```
type - Required field. Default to sw.application.
```

Which (a) isn't helpful and (b) poses the question how a required field can have a default?

**Comment by vipulgupta2048** [comment]
@Hades32 That was the exact question I had when I wrote this bit in release party #2. The answer IIRC is that the contract only allows for this value at the moment and `type` is required for DWB or host them on balenaHub. We are most likely to add more context to this as balenaHub expands so do its usecases. It isn't helpful but it is very much required for the current context. @chrisys can expand further on this if we can add more information for this now.

**Comment by Hades32** [comment]
Ah I see, just like k8s resources always have a `kind` and `api` field...

So a good description might be this maybe?
```
type - the kind of resource described by this YAML file. Only 'sw.application' is supported at the moment
```

**Comment by vipulgupta2048** [comment]
@Hades32  Yeah, that seems better. We can make a PR & get more comments.

**Comment by vipulgupta2048** [comment]
Stevche's PR https://github.com/balena-io/docs/pull/1577/files, solves this by providing more context on this.
