### ISSUE TITLE
chore: Remove is_on__commit example from API 

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-io/docs#1565]
In v6 of the API, is_on__commit field doesn't exist hence this example would not be useful now.  https://www.balena.io/docs/reference/api/resources/device/#get-current-release

cc: @dfunckt should we just remove this example now?

**Comment by dfunckt** [comment]
@vipulgupta2048 good shout -- I think the example is for a very common use case and we should strive to update it. Ping me in FD and I can help you navigate this.

**Comment by vipulgupta2048** [comment]
Context: https://www.flowdock.com/app/rulemotion/i-docs/threads/aHoo0fsWG4B38wlwp8tTvRctp5c
Patch desciption for https://www.balena.io/docs/reference/api/resources/device/#get-target-release
And, delete https://www.balena.io/docs/reference/api/resources/device/#get-current-release
