### ISSUE TITLE
Document the maximum length and size of environment variable values

### ISSUE THREAD

**Issue by gelbal** [balena-io/docs#1572]
As a user, I'd like to know the size constraints of the environment and service variable values in advance, so I could build my application accordingly.

**Comment by vipulgupta2048** [comment]
@gelbal I remember this support thread, what was the conclusion on the size constraints. I see Thodoris has replied with an answer, can you reach back to the user about the constraint of having large environment variables if they go ahead with it. 

On our side, we can add that there is no limit to size of variables though large variables could lead to added traffic? Just to confirm that's traffic on their side if I read it right. Let me know.

**Comment by pranasziaukas** [comment]
IMO it makes sense to enforce some kind of sane limit, otherwise it's an open opportunity for abuse.
Of course, the question to enforce a limit or not is outside the scope of the docs repo.

**Comment by gelbal** [comment]
@vipulgupta2048 I already reached out to the user, gave this issue's link and affirmed that going up to 1MB in size shouldn't be a problem -- if that's what you are asking for. 

I'm with Pranas that it's sensible to enforce a limit here to prevent abuse. Let's raise it as a product call discussion before we update the docs.

**Comment by vipulgupta2048** [comment]
Thanks @gelbal that be a much better way to go about this tbh.

**Comment by gelbal** [comment]
We decided to document 1MB as the limit which should be more than sufficient. 
Brainstorm discussion here: https://jel.ly.fish/8f9081b6-5962-471a-a699-ec078b70d881
