### ISSUE TITLE
User would like us to add something to docs re. node_modules to . docker_ignore 

### ISSUE THREAD

**Issue by Jazzagi** [balena-io/docs#1574]
User feedback survey response:

When pushing a (node.js) project to the devices, I inadvertently overwrote node-gyp platform specific files in node_modules which is more a user error than anything to do with balena.
Could be an edge case related to having build the project on the development laptop and copying all files using docker)
Yet a mention of this in the docs or adding node_modules to . docker_ignore for the node quick start template could prevent this. After this hurdle, things went pretty smooth and overal impressed with ease of use.

https://app.frontapp.com/inboxes/teams/folders/30943/unassigned/20572681485

**Comment by vipulgupta2048** [comment]
Good one and good tip @Jazzagi We can add a note for folks to add node_modules to  .dockerignore for faster, reliable builds.
@stathismor Something for you to check out since you are working on the new Typescript Hello World example as well.

**Comment by stathismor** [comment]
Yup, I've been a victim of this! My new repo has `node_modules` in `.dockerignore`. I will push for using this in the getting started guide, feel free to review if you have time. https://github.com/balena-io-playground/balena-ts-node-hello-world/pull/1

**Comment by stathismor** [comment]
@vipulgupta2048 we should just add the `node_modules` ourselves I think, in our JS Node repo. The issue I had faced, that took a while to debug, was that my laptop's `node_modules` were overwriting the fin's modules. And although the files there all looked the same, I was getting build errors, probably because of the different npm implementation in the two different machines.

**Comment by stathismor** [comment]
@Jazzagi @vipulgupta2048 this now should be resolved as part of https://github.com/balena-io-examples/balena-node-hello-world/pull/32
