### ISSUE TITLE
API: document device_tag PATCH method

### ISSUE THREAD

**Issue by pdcastro** [balena-io/docs#1587]
There are docs for GET and POST:
https://www.balena.io/docs/reference/api/resources/device_tag/#create-tag

But it's missing a PATCH example:

```
curl -X PATCH \
  "https://api.balena-cloud.com/v6/device_tag?\$filter=device/uuid%20eq%20'$BALENA_DEVICE_UUID'" \
  -H "Authorization: Bearer $BALENA_API_KEY" \
  -H "Content-Type: application/json" \
  --data '{ "tag_key": "c", "value": "e" }'
```

**Comment by vipulgupta2048** [comment]
@pdcastro The POST example is demonstrating the same functionality, is it necessary to have a PATCH example too?

**Comment by pdcastro** [comment]
> @pdcastro The POST example is demonstrating the same functionality, is it necessary to have a PATCH example too?

@vipulgupta2048, I think so, because:
* The POST example does not quite demonstrate the same functionality or syntax. Using POST for an existing device tag results in an error: ""device" and "tag_key" must be unique". The POST request uses a numeric device ID in the request body, while the PATCH request uses a device UUID in a $filter query string.
* The user in the support thread was looking for an example of how to update a device tag using the API and couldn't find it or figure it out by themselves, then two support agents (one of them being me) also had to spend time trying to come up with a working example to help the user. If the user or the support agents were more knowledgeable about the API requests and resources, the extra examples would not be needed, but this wasn't the case.
* As Alexandros usually says, a user who comes to support represents many other users who struggled in silence or gave up.

I have created PR #1588 to add the examples - pending review.
