### ISSUE TITLE
Remove meniton of update-resin-supervisor for upgrading the supervisor

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/docs#1594]
https://www.balena.io/docs/learn/more/masterclasses/device-debugging/#82-updating-the-supervisor

**Comment by vipulgupta2048** [comment]
@20k-ultra I see how we missed this out from the recent PR someone made to do just that. Since masterclasses are externally sourced, the PR needs to be made here instead https://github.com/balena-io/debugging-masterclass

**Comment by 20k-ultra** [comment]
funny because I made https://github.com/balena-io/debugging-masterclass/pull/24 and forgot to update it...I'll continue working on that one
