### ISSUE TITLE
CI/CD check to check for broken links

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-io/docs#1621]
Broken links ain't fun. Since the entire site is auto-generated, we can check for broken links when the site is being built in the Docker build step (Suggestions welcome)

Work needed to be done: Contributor assesses the tool, checks if they are suitable, add them to the CI/CD pipeline. As an additional step, broken links can be fixed in another PR while assessing the tool. 

1. https://github.com/becheran/mlc as a GitHub Action (Easiest?)
2. https://github.com/lycheeverse/lychee as GitHub Action (Could be better? Check comparison table)
3. https://github.com/stevenvachon/broken-link-checker
4. and more if they are suitable. 

Need to make sure that the tool is able to parse every page of the documentation even those that are dynamically presented only when requested.

**Comment by 20k-ultra** [comment]
This is a neat issue! We should try to make this generic enough that it can be added to any repository...call it 404 sniffer :p 

We could then utilize something like this on resin-site or any other repos with a front end with documentation.

**Comment by 20k-ultra** [comment]
I spoke too soon before checking those links. Seems like this has been solved a few different ways already and it's just a matter of picking our favorite flavor.

**Comment by 20k-ultra** [comment]
we'll just have to experimenting with the projects and see which works but least amount of effort since this is just a nice to have.

**Comment by LucianBuzzo** [comment]
One of the main issues we have here is rate limiting. GitHub actions are [rate limited to 1000 requests per hour](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) and a check will go through many more than that. I noticed that we are checking a lot of base image links, so we can probably compromise by skipping them.
