### ISSUE TITLE
Getting started guide needed for FireFly RK3288

### ISSUE THREAD

**Issue by acostach** [balena-io/docs#1633]
This is a community device type, maintained by our user from which we forked the repository: https://github.com/balena-os/balena-rockchip-rk3288

Please file a ticket with the link to the docs in the above repository so we can update the coffee file when ready

**Comment by vipulgupta2048** [comment]
There is a getting started guide needed for this device. Refer to the following PR's as a guide to add a new device type Getting Started.

1. #1596
2. #1182
3. #1087
