### ISSUE TITLE
Getting started needed for Etcher Pro

### ISSUE THREAD

**Issue by acostach** [balena-io/docs#1645]
Device repository present at: https://github.com/balena-os/balena-compulab

Getting started link points to: http://docs.resin.io/etcher-pro/getting-started/#adding-your-first-device

**Comment by vipulgupta2048** [comment]
There is a getting started guide needed for this device. Refer to the following PR's as a guide to add a new device type Getting Started.

1. #1596
2. #1182
3. #1087

**Comment by mpous** [comment]
I changed the Getting started links [here](https://github.com/balena-os/balena-compulab/pull/69) to don't get 404
