### ISSUE TITLE
Getting started needed for NPE X500 M3 (community, RPI3 based Device Type)

### ISSUE THREAD

**Issue by acostach** [balena-io/docs#1646]
Currently re-uses RaspberryPi 3 getting started: https://www.balena.io/docs/learn/getting-started/raspberrypi3/nodejs/

**Comment by vipulgupta2048** [comment]
There is a getting started guide needed for this device. Refer to the following PR's as a guide to add a new device type Getting Started.

1. #1596
2. #1182
3. #1087
