### ISSUE TITLE
Getting started needed for Odroid XU4

### ISSUE THREAD

**Issue by acostach** [balena-io/docs#1651]
Getting started points to http://docs.resin.io/#/pages/installing/gettingStarted-ODROID-XU4.md#on-mac-and-linux currently

**Comment by vipulgupta2048** [comment]
There is a getting started guide needed for this device. Refer to the following PR's as a guide to add a new device type Getting Started.

1. #1596
2. #1182
3. #1087

**Comment by jakogut** [comment]
@vipulgupta2048 It appears there is already a getting started guide published: https://www.balena.io/docs/learn/getting-started/odroid-xu4/nodejs/

We may just need to update the links.

**Comment by jakogut** [comment]
It looks like the links have already been updated, actually. The new release simply hasn't been deployed yet.

https://github.com/balena-os/balena-odroid/commit/2d55b87c08f74ef95fbc511e7620fe59220be2be

Indeed, looking at the staging dashboard, the getting started guide links to https://www.balena.io/docs/learn/getting-started/odroid-xu4/nodejs/ as it should.

This issue should be fixed simply by issuing a new release on production.

**Comment by vipulgupta2048** [comment]
Thanks @jakogut 
cc: @acostach to check if they are no further actions required for the same.
