### ISSUE TITLE
IBM Bluemix integration docs are out of date

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io/docs#1656]
The screenshots used in the IBM Bluemix docs are out of date and show quite an old version of the dashboard. https://www.balena.io/docs/learn/develop/integrations/bluemix/

**Comment by phil-d-wilson** [comment]
IBM bluemix was renamed `IBM Cloud` in 2017. I don't think the screenshots will be the only thing out of date here. I think we should probably check that guide in it's entirety, rather than just the screenshots.

**Comment by kb2ma** [comment]
IBM Bluemix docs were removed with the 3rd party integration update in #2329.
