### ISSUE TITLE
Missing getting started images for ConnectCore 8X SBC Pro

### ISSUE THREAD

**Issue by alexgg** [balena-io/docs#1662]
Internal thread https://www.flowdock.com/app/rulemotion/i-docs/threads/SQbHURKhp0X5EPM1m22IlvlFUBv

The getting started is generated but the images need to be uploaded.

**Comment by vipulgupta2048** [comment]
While a lot many are missing images, I remember @alexgg mentioning this one. We can add images for this one next. On my side, I will start sorting stuff with old images and Getting Started in general.
