### ISSUE TITLE
Broken link on getting started guide - Alpine Linux Distro

### ISSUE THREAD

**Issue by Jazzagi** [balena-io/docs#1743]
Broken link in 'Alpine Linux Distro' in following sentence:

Now we will create a minimal node.js container based on the slim Alpine Linux distro. We do this by adding the following lines to our Dockerfile.

Link to section of GSG - https://www.balena.io/os/docs/raspberrypi3/getting-started/#Creating-a-Project-from-Scratch

Broken url - https://www.balena.io/os/docs/raspberrypi3/getting-started/link-to-alpine

Update - This is broken on all versions of the gsg so needs updating for each device type

**Comment by vkarathanasi** [comment]
The right link is https://hub.docker.com/r/balenalib/raspberrypi3-alpine-node

This is the page where the link is wrong https://github.com/balena-os/balena-os/blob/master/pages/docs/gettingstarted.md

**Comment by vipulgupta2048** [comment]
Closing issue in favor of https://github.com/balena-os/balena-os/pull/560
