### ISSUE TITLE
Broken link to Fin kit on Masterclass advanced CLI page

### ISSUE THREAD

**Issue by Jazzagi** [balena-io/docs#1749]
Docs page where broken link appears: https://www.balena.io/docs/learn/more/masterclasses/advanced-cli/

Sentence containing broken link: A balena supported device, such as a balenaFin 1.1, Raspberry Pi 3 or Intel NUC. If you don't have a device, you can emulate an Intel NUC by installing VirtualBox and following this guide

  Broken url: https://store.balena.io/collections/developer-kit/products/balenafin-v1-1-0-developer-kit

Broken link should be replaced with: https://store.balena.io/collections/developer-kit/products/balenafin-developer-kit-v1-1-cm3-l

**Comment by Jazzagi** [comment]
@vipulgupta2048 @andrewnhem Tried to PR this but it got a bit complicated and i think i ended up creating a PR elsewhere :/ 

I was informed I should fork the repo, so i followed the instructions and ended up with this - https://github.com/balena-io/balena-cli-advanced-masterclass/pull/32

Which appears to not even be in docs.

**Comment by andrewnhem** [comment]
@Jazzagi No worries! Let's see how the review goes. Thanks for hunting that down!

**Comment by toochevere** [comment]
This seems to already be fixed in `master`
```
* A balena supported device, such as a [balenaFin 1.1](https://store.balena.io/collections/developer-kit/products/balenafin-developer-kit-v1-1-cm3-l),
```
