### ISSUE TITLE
Broken link on base images/installingyourowninitsystem

### ISSUE THREAD

**Issue by Jazzagi** [balena-io/docs#1751]
Docs page where broken link appears: https://www.balena.io/docs/reference/base-images/base-images/#installing-your-own-initsystem

Sentence containing broken link:   Generally, for systemd, it just requires installing the systemd package, masking a number of services and defining a new entry.sh and a balena.service. The Dockerfile below demonstrates this:

Broken url: https://github.com/balena-io-library/base-images/tree/master/examples/INITSYSTEM/systemd/systemd.v230/balena.service

**Comment by vipulgupta2048** [comment]
Correct link seems to be https://github.com/balena-io-library/base-images/blob/master/examples/INITSYSTEM/systemd/systemd.v230/resin.service
