### ISSUE TITLE
Broken link api/resources/application/

### ISSUE THREAD

**Issue by Jazzagi** [balena-io/docs#1756]
Docs page where broken link appears: https://www.balena.io/docs/reference/api/resources/application/

Sentence containing broken link:   'Improve this doc' (lol)

Broken url: https://github.com/balena-io/docs/edit/master/pages/reference/api/resources/application.md

**Comment by catt-tung** [comment]
Link should be https://github.com/balena-io/docs/edit/master/pages/reference/api/resources.md instead

**Comment by vipulgupta2048** [comment]
Resolved with https://github.com/balena-io/docs/pull/2362
