### ISSUE TITLE
Broken link on balena-cli/#os-configure-image

### ISSUE THREAD

**Issue by Jazzagi** [balena-io/docs#1757]
Docs page where broken link appears: https://www.balena.io/docs/reference/balena-cli/#os-configure-image

Sentence containing broken link:  

The --system-connection (-c) option can be used to inject NetworkManager connection profiles for additional network interfaces, such as cellular/GSM or additional WiFi or ethernet connections. This option may be passed multiple times in case there are multiple files to inject. See connection profile examples and reference at: https://www.balena.io/docs/reference/OS/network/2.x/ https://developer.gnome.org/NetworkManager/stable/nm-settings.html

Broken url: https://developer.gnome.org/NetworkManager/stable/nm-settings.html

**Comment by markcorbinuk** [comment]
PR generated here https://github.com/balena-io/balena-cli/pull/2235

**Comment by vipulgupta2048** [comment]
Closing in favor of https://github.com/balena-io/balena-cli/pull/2235
