### ISSUE TITLE
Broken link on resources/whoami/

### ISSUE THREAD

**Issue by Jazzagi** [balena-io/docs#1758]
Docs page where broken link appears: https://www.balena.io/docs/reference/api/resources/whoami/

Sentence containing broken link:  Improve this doc (lol)

Broken url: https://github.com/balena-io/docs/edit/master/pages/reference/api/resources/whoami.md

**Comment by toochevere** [comment]
This is a bigger issue than a simple broken link.  _Any_ selected resource results in the same thing.  Not sure if this needs to be reclassified to Intermediate.  @vipulgupta2048

**Comment by vipulgupta2048** [comment]
Hello @toochevere I checked this out for some time when Jasmine opened it. Currently the API documentation is generated from this file https://github.com/balena-io/docs/blob/master/config/dictionaries/resource.json, it might be a good idea for the Improve the docs button to point to this file instead. We are not there yet on the automatic generation of the API documentation. They still are updated manually. Additionally don't worry about the classification, it was only for the release party. 

Do let me know if you like to help us out with automatic generation of the API documentation, @thgreasi would be the happiest person if you do

**Comment by vipulgupta2048** [comment]
Resolve with #2362
