### ISSUE TITLE
Python dbus example broken in Python3

### ISSUE THREAD

**Issue by alanb128** [balena-io/docs#1771]
Page: https://www.balena.io/docs/reference/OS/network/2.x/#changing-the-network-at-runtime

Line `'ssid': dbus.ByteArray(SSID),` should be `'ssid': dbus.ByteArray(SSID.encode()),`

**Comment by jakogut** [comment]
It looks like I incorrectly thought this was not py2 compatible when it is. It looks like the default encoding is 'utf-8'.
