### ISSUE TITLE
Update Public Roadmap link in learn/welcome/introduction/

### ISSUE THREAD

**Issue by apostolism** [balena-io/docs#1805]
The public roadmap link in https://www.balena.io/docs/learn/welcome/introduction/ points to a public Trello board under a personal account of a previous team member (Shaun) which also hasn't been updated since January 2021. 

This should point to a public Trello that's part of the balena org in Trello instead.

Current public Trello board link: https://trello.com/b/9CSzdCXQ/balena-product-roadmap

**Comment by vipulgupta2048** [comment]
@apostolism Can you post the updated Trello board link?

**Comment by apostolism** [comment]
@vipulgupta2048 we haven't created a new Trello board yet. Should it be just a copy of the existing one?

**Comment by vipulgupta2048** [comment]
> This should point to a public Trello that's part of the balena org in Trello instead.

@apostolism I don't understand. I thought an updated board already exists that's why you opened an issue to get it updated?

**Comment by apostolism** [comment]
@chrisys is an admin of that Trello board, and he updated the board settings. The board now is under the balena org in Trello and no further update is needed. Closing the issue.
