### ISSUE TITLE
Add generic global link to balenaHub

### ISSUE THREAD

**Issue by somombo** [balena-io/docs#1812]
> @vipulgupta2048: Add balenaHub to links.coffee file for it to be referenced later - https://github.com/balena-io/docs/blob/master/config/links.coffee I assume we would like to add balenaHub a lot of times throughout the docs 
>
> Adding it to links module helps us refer to it consistently all over the place. Check this for reference https://github.com/balena-io/docs/blob/790bb6ebc1640a8526a9672547286bf866476d1e/CONTRIBUTING.md#adding-links-to-the-docs

We also need to track down all the other hard coded links and replace them with the generic one

and more things  https://github.com/balena-io/docs/issues/1812#issuecomment-814090205

**Comment by vipulgupta2048** [comment]
More things to be added in this [JF thread](https://www.flowdock.com/app/rulemotion/i-docs/threads/zPzdVMc37J2ZaD5x5nhklyYTFGB)

**Comment by vipulgupta2048** [comment]
@somombo Are you still working on this?

**Comment by vipulgupta2048** [comment]
@somombo Are you still working on this?

**Comment by somombo** [comment]
> @somombo Are you still working on this?

Yes @vipulgupta2048  i am working on it today. Sorry started Friday, then got sidetracked
