### ISSUE TITLE
Provide better documentation for the "VPN Only" status

### ISSUE THREAD

**Issue by ntzovanis** [balena-io/docs#1818]
Currently, the [device statuses](https://www.balena.io/docs/learn/manage/device-statuses/) page doesn't contain any information about the "VPN only" status. If a customer googles it, they won't find any clear answer of what that means.

**Comment by vipulgupta2048** [comment]
@srlowe how about this one, if you are looking for issues to solve. Thodoris recently added more docs to this page yet some folks are having trouble understanding the statuses. We can add more context to this page and explain the statuses even better.

**Comment by srlowe** [comment]
@vipulgupta2048 Sure, I'll take this one
