### ISSUE TITLE
Clarify How Team Member Roles are Retained During The Application Transfer Instructions -

### ISSUE THREAD

**Issue by joehounsham** [balena-io/docs#1826]
https://www.balena.io/docs/learn/manage/actions/#transfer-application-ownership

The current instructions don't explain that the source application team members retain their membership roles when moving to the target application. 

The instructions also don't clarify that the source application owner doesn't retain membership of the target application of any kind, so they need to be re-added as an application member if necessary.

**Comment by vipulgupta2048** [comment]
Closing PR in favor of #1832
