### ISSUE TITLE
Different network requirements whitelist on Docs and FAQs

### ISSUE THREAD

**Issue by mpous** [balena-io/docs#1890]
There are two documents related with Network requirements in order to whitelist balena domains.

This one [here](https://www.balena.io/docs/reference/OS/network/2.x/#network-requirements) refers to whitelist ```*.balena-cloud.com``` domain.

The FAQs [here](https://www.balena.io/docs/faq/troubleshooting/faq/#what-network-ports-are-required) mention that the whitelist should be more domains.

Need to check which suggestion is correct.

**Comment by vipulgupta2048** [comment]
@mpous Not sure I get it, the FAQ question links to the page you mentioned before it. How are the suggestions different? 
cc: @pranavpeshwe Who recently edited these pages.

**Comment by mpous** [comment]
ok @vipulgupta2048 this is different that what i saw some days ago! maybe there was an issue that i didn't find when i submitted this issue! Glad that this is solved :)
