### ISSUE TITLE
Should add docs page for device metrics as reported from the Supervisor

### ISSUE THREAD

**Issue by cywang117** [balena-io/docs#1901]
Should differentiate between System Checks and System Metrics. Per balena-os/balena-supervisor#1666, we've separated out metrics reporting into optionally reported `System Metrics` and always-reported `System Checks`. This is specified in the `Required?` column of the table below, not required indicating a System Metric.

Should mention that System Metrics are not reported when a user-toggleable `{BALENA|RESIN}_SUPERVISOR_HARDWARE_METRICS` is false. In this case the UI will grey out appropriately. See https://github.com/balena-io/balena-ui/issues/4726.

Device Metrics:
| Name | Type | Description | Supervisor Slug | Required? |
|----|----|----|----|----|
| CPU Utilization | integer (%) |  Utilization percentage of the CPU. Receive updates when the “bucket” of the CPU usage changes past certain milestones in increments of 20%. | cpu_usage | false |
| CPU Temperature | integer (°C) | CPU temperature in degrees Centigrade in boundaries of 3 degrees, subject to bandwidth saving transfer strategies. | cpu_temp | false |
| Memory Usage | integer (Mb) | RAM usage on the device in megabytes. | memory_usage / memory_total | false | 
| Disk Storage | integer (Mb) | Utilized storage and total storage in megabytes. | storage_usage / storage_total | false |
| Undervoltage | boolean | Detect power supply insufficiency. Not supplying enough power most commonly leads to power brownouts or disk corruption. Will NOT toggle back to false after true has been reported until reboot occurs. | is_undervolted | true |

Related: #1497

**Comment by vipulgupta2048** [comment]
Good stuff @cywang117 Would you be making a PR for this? We can add this information to a new page or the existing device status page as I mentioned before.

**Comment by cywang117** [comment]
@vipulgupta2048 For sure! I think when the Supervisor version with HARDWARE_METRICS (balena-os/balena-supervisor#1666) is deployed to production would be a good time to add this page so we don't have to come back and make any changes (such as adding what SUPERVISOR_HARDWARE_METRICS does)

**Comment by vipulgupta2048** [comment]
SGTM, looking forward to it. The blog on metrics can then be redirected here
