### ISSUE TITLE
Pages loop-reload when attaching `?ref=dockerhub` to URL

### ISSUE THREAD

**Issue by cywang117** [balena-io/docs#1935]
https://www.balena.io/docs/learn/getting-started/qemux86/nodejs/?ref=dockerhub is an example of this behavior, but this is reproducible by attaching `?ref=dockerhub` to any URL on the site.

From what I experienced, `?ref=dockerhub` is attached to the docs URL when I visit the page from its Google search listing. But substituting `dockerhub` with anything else will also result in a reload loop.

**Comment by lurch** [comment]
Looks similar to https://github.com/balena-io/etcher/issues/3485 ?

**Comment by cywang117** [comment]
@lurch Thanks for the share! It looks like reload loops will be triggered by attaching `?ref=<STRING>`, where STRING could literally be anything.

**Comment by aethernet** [comment]
it's not limited to `?ref`, any parameter added to the url will trig the infinite reload

**Comment by aethernet** [comment]
This line cause the issue : https://github.com/balena-io/docs/blob/51f200796379ac0cf29fca951658462b53c6ea3b/templates/_track.html#L19

Reading the docs [Analytics-Client](https://www.npmjs.com/package/analytics-client) it's not clear to me if we should clean up the querystring or not.

My understanding so far is that the intent is to move the deviceId out of the url in case the user copy/paste/share the url later on.

My fix is to only update the querystring if the cleanup function returned something different.

We could also remove the 3 lines all together

Fix is #2231
