### ISSUE TITLE
Create a doc for Fleet actions

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/docs#1973]
The [member types](https://www.balena.io/docs/learn/manage/account/#member-types) table has a "Fleet actions" heading but it's unclear what that is.

**Comment by vipulgupta2048** [comment]
@20k-ultra We already have actions documentation it seems like, what we need to document is Settings, no?
https://www.balena.io/docs/learn/manage/actions/#actions

**Comment by 20k-ultra** [comment]
That links to explain Fleet actions. The issue is we don't use the fleet anywhere in the dashboard. A fleet is actually an application in the dashboard but you and I know a Fleet refers to N devices in an application.

Closing this issue and will discuss more in https://github.com/balena-io/docs/pull/1932 as that is where I wanted to use new doc.

**Comment by vipulgupta2048** [comment]
Thanks, I will open an issue for the creation of docs page for the Settings.
