### ISSUE TITLE
balenaOS: partitions diagram incorrectly displays boot and rootA/B partitions as read only

### ISSUE THREAD

**Issue by tmigone** [balena-io/docs#1982]
Diagram here: https://www.balena.io/docs/reference/OS/overview/2.x/#stateless-and-read-only-rootfs

It states `resin-boot`, `resin-rootA` and `resin-rootB` are "read only" while `resin-state` and `resin-data` are `read/write`.
In reality all of them are mounted as `rw` in balenaOS:

```
root@d42d6a2:/mnt/boot# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
mmcblk0     179:0    0  29.7G  0 disk
|-mmcblk0p1 179:1    0    40M  0 part /mnt/boot
|-mmcblk0p2 179:2    0   312M  0 part /mnt/sysroot/active
|-mmcblk0p3 179:3    0   312M  0 part /mnt/sysroot/inactive
|-mmcblk0p4 179:4    0     1K  0 part
|-mmcblk0p5 179:5    0    20M  0 part /mnt/state
`-mmcblk0p6 179:6    0    29G  0 part /mnt/data
zram0       254:0    0 480.3M  0 disk [SWAP]
root@d42d6a2:/mnt/boot# findmnt | grep -e mmcblk -e uuid
|-/mnt/sysroot/active                    /dev/disk/by-uuid/ba1eadef-0170-4242-9221-7354f6c37db9                              ext4       rw,relatime
|-/mnt/data                              /dev/mmcblk0p6                                                                      ext4       rw,relatime
|-/mnt/boot                              /dev/mmcblk0p1                                                                      vfat       rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro
| `-/mnt/sysroot/inactive                /dev/mmcblk0p3                                                                      ext4       rw,relatime
|-/resin-data                            /dev/mmcblk0p6[/resin-data]                                                         ext4       rw,relatime
| |-/var/volatile/lib/docker             /dev/mmcblk0p6[/docker]                                                             ext4       rw,relatime
| |-/var/lib/docker                      /dev/mmcblk0p6[/docker]                                                             ext4       rw,relatime
```

For details see: https://www.flowdock.com/app/rulemotion/public-s-community/threads/x8Rgs067mIto4OQ6ThUe471Da94

**Comment by vipulgupta2048** [comment]
IIRC I think we recently created a new diagram for a blog I was working with @andrewnhem Have to check which blog and if it is actually new. Checking

**Comment by andrewnhem** [comment]
@vipulgupta2048 @tmigone talking about this one?

![image](https://user-images.githubusercontent.com/8039239/126010154-f2a07447-bcd5-4300-852d-ab65af1a91b0.png)

From [Feb 2021 Offline Updates post](https://www.balena.io/blog/offline-updates-make-it-easier-to-update-balena-devices-without-the-internet/).

**Comment by klutchell** [comment]
I think the only incorrect thing there is `Boot partition` is actually `read-write`.

**Comment by markcorbinuk** [comment]
Also applies to this one https://www.balena.io/docs/reference/OS/overview/2.x/#image-partition-layout

**Comment by tmigone** [comment]
@klutchell root partitions are also writable according to my (limited) testing.

**Comment by klutchell** [comment]
@tmigone It may have looked that way since some directories have the read-write state partition overlayed on top of the active root partition which is otherwise read-only.

```bash
root@1582068:~# mount | grep state
/dev/mmcblk0p5 on /mnt/state type ext4 (rw,relatime)
root@1582068:~# mount | grep 0p5  
/dev/mmcblk0p5 on /mnt/state type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/machine-id type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/fake-hwclock type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/NetworkManager/conf.d type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/NetworkManager/system-connections type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/docker type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/balena-supervisor type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/hostname type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/openvpn type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/ssh/hostkeys type ext4 (rw,relatime)
/dev/mmcblk0p5 on /etc/udev/rules.d type ext4 (rw,relatime)
/dev/mmcblk0p5 on /home/root/.docker type ext4 (rw,relatime)
/dev/mmcblk0p5 on /home/root/.rnd type ext4 (rw,relatime)
/dev/mmcblk0p5 on /home/root/.ssh type ext4 (rw,relatime)
/dev/mmcblk0p5 on /usr/share/ca-certificates/balena type ext4 (rw,relatime)
/dev/mmcblk0p5 on /var/lib/NetworkManager type ext4 (rw,relatime)
/dev/mmcblk0p5 on /var/volatile/lib/NetworkManager type ext4 (rw,relatime)
/dev/mmcblk0p5 on /var/lib/bluetooth type ext4 (rw,relatime)
/dev/mmcblk0p5 on /var/volatile/lib/bluetooth type ext4 (rw,relatime)
/dev/mmcblk0p5 on /var/lib/chrony type ext4 (rw,relatime)
/dev/mmcblk0p5 on /var/volatile/lib/chrony type ext4 (rw,relatime)
/dev/mmcblk0p5 on /var/lib/systemd type ext4 (rw,relatime)
/dev/mmcblk0p5 on /var/volatile/lib/systemd type ext4 (rw,relatime)
```
So on my device any files/directories not in the above list will be read-only. It's a long list of exceptions, and one we wish were shorter to be sure. But it also means we are very intentional when we make a directory read-write, as the default is always read-only.

**Comment by vipulgupta2048** [comment]
@klutchell Should we change the diagram then to reflect the current scheme?

**Comment by klutchell** [comment]
@vipulgupta2048 Yeah, I don't know who has the source for this .png but the boot partition should be changed to read-write.
https://www.balena.io/docs/reference/OS/overview/2.x/#stateless-and-read-only-rootfs

Or switch to the new image and make the corrections I listed above.

> I think the only incorrect thing there is Boot partition is actually read-write and I think it always has been.
> Also the second and third columns should be Root partition A/B, not "Boot".

**Comment by andrewnhem** [comment]
@apexider : Can you please update this image? it's the one we created and used for [this blog post (third diagram)](https://www.balena.io/blog/offline-updates-make-it-easier-to-update-balena-devices-without-the-internet/). Let me know if you need any help interpreting the above.

Corrections by @klutchell and crew:

* Boot partition is actually read-write and I think it always has been.
* Also the second and third columns should be **Root** partition A/B, not "Boot".

**Comment by apexider** [comment]
@andrewnhem [Here](https://drive.google.com/open?id=1mlO886rItlZbeSKOtYefWO_rgGBrBBWR) I updated the diagram to have "read-write" for "boot partition" for both, the post and for the docs :)

cc @klutchell

**Comment by klutchell** [comment]
Thanks @apexider! I added some comments to the images, but it looks good otherwise!

1. The two A/B partitions are supposed to be `Root` not `Boot`
2. One of the images says `AUDS` for the data partition instead of `AUFS`

**Comment by apexider** [comment]
@klutchell oh sorry and thank you for the annotations! I've updated the images :)

**Comment by klutchell** [comment]
Looks good @apexider, thank you!

@vipulgupta2048 How do we update the image in the docs?

**Comment by andrewnhem** [comment]
@klutchell @vipulgupta2048 Imperfect solution here, but I've added both to our assets repo:

- docs version: https://assets.balena.io/blog-common/2021/07/boot-partition-docs.jpg
- blog version: https://assets.balena.io/blog-common/2021/07/boot-partition-blog.png

I will update the Offline Updates post. Feedback and questions welcome.
