### ISSUE TITLE
BalenaBlocks page still mentions resin

### ISSUE THREAD

**Issue by lurch** [balena-io/docs#1985]
I just noticed that https://www.balena.io/docs/learn/more/examples/balenablocks/ says "a node-red application with balena-supervisor support, can be managed remotely via resin publicURL" - I suspect it ought to say "balena publicURL" ?

**Comment by klutchell** [comment]
Good catch! Thanks for bringing it to our attention!

This page is actually auto-generated with the GitHub API, so it's the [balena-node-red repo](https://github.com/balenablocks/balena-node-red) that needs to update the **About** field. It looks like the README has already been updated but we are using the repo description to populate the table. 

```
curl https://api.github.com/orgs/balenablocks/repos\?per_page\=30 | jq -r 'sort_by(-.stargazers_count) |  (.[] | [.name,.html_url,.description] | "[\(.[0])](\(.[1]))|\(.[2] // "")") '
```
```
...
[balena-node-red](https://github.com/balenablocks/balena-node-red)|a node-red application with balena-supervisor support, can be managed remotely via resin publicURL
[browser](https://github.com/balenablocks/browser)|A drop-in web browser block
[audio](https://github.com/balenablocks/audio)|Audio building block, based on pulseaudio.
...
```
