### ISSUE TITLE
supervisor update strategy docs link 404s

### ISSUE THREAD

**Issue by robertgzr** [balena-io/docs#2007]
1. go to https://www.balena.io/docs/reference/supervisor/supervisor-api/
2. try to go to the 'Upgrade policy' link in the sidebar
3. the link 404s

I think this is the page that used to show up: https://www.balena.io/docs/learn/deploy/release-strategy/release-policy/ ?

cc @20k-ultra @cywang117 

cc @vipulgupta2048 why didn't the link checker catch this? is it because these docs come from the supervisor repo?

**Comment by vipulgupta2048** [comment]
Maybe this is the case of the upgrade policy being removed, but not removed from the sidebar. 
Regarding link checker we should surely look into why it's not checking the sidebar links
Regarding this page, https://www.balena.io/docs/learn/deploy/release-strategy/release-policy/ - I felt this to be a supervisor page. Maybe we should backlink this somewhere in the Supervisor docs. So folks coming to find it and refer to that./

**Comment by vipulgupta2048** [comment]
@20k-ultra @cywang117 bringing this up again to find a resolution for this.

**Comment by 20k-ultra** [comment]
So the upgrade policy was removed in https://github.com/balena-os/balena-supervisor/pull/1642 so the docs could reference its own documentation of this which is located in https://github.com/balena-io/docs/blob/master/pages/reference/supervisor/supervisor-upgrades.md.

Side note, now that the Supervisor repo doesn't mention it cannot be downgraded I made https://github.com/balena-os/balena-supervisor/pull/1782 to fix that.

So, to fix this issue we must update https://github.com/balena-io/docs/blob/master/config/navigation.txt to point "Upgrade Policy"  to https://github.com/balena-io/docs/blob/master/pages/reference/supervisor/supervisor-upgrades.md.

**Comment by 20k-ultra** [comment]
Actually, that Upgrade Policy link should just be removed since http://localhost:3000/docs/reference/supervisor/supervisor-upgrades/ supersedes it entirely. There is a subheading in that page called [upgrade paths](http://localhost:3000/docs/reference/supervisor/supervisor-upgrades/#upgrade-paths) which explains the same content the previous "upgrade policy" page had.

**Comment by 20k-ultra** [comment]
Issue will be closed once https://github.com/balena-io/docs/pull/2068 is automatically merged because I self-certified.

We will have to look into why the 404 was caught by our checker though @vipulgupta2048
