### ISSUE TITLE
BalenaOS website lists Raspberry Pi 1 twice

### ISSUE THREAD

**Issue by lurch** [balena-io/docs#2018]
At https://www.balena.io/os/#download

![Screenshot from 2021-08-06 16-46-01](https://user-images.githubusercontent.com/476186/128536938-6fb8548c-6e7c-483f-a1be-e1689dacc943.png)

**Comment by vipulgupta2048** [comment]
Fixed now

**Comment by lurch** [comment]
Thanks @vipulgupta2048 
While checking that it was fixed, I noticed that you (incorrectly) refer to "[Raspberry Pi Zero 2 W](https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/)" as "Raspberry Pi Zero 2 Wifi".

And whilst clicking around I also noticed that https://www.balena.io/os/docs/supported-boards/ incorrectly capitalises "[Raspberry Pi Zero](https://www.raspberrypi.com/products/raspberry-pi-zero/)" as "Raspberry Pi ZERO"; and that page also doesn't list the ARMv8 architecture used by [Raspberry Pi 4 Model B](https://www.raspberrypi.com/products/raspberry-pi-4-model-b/) ?

https://www.balena.io/docs/reference/hardware/devices/ is also using the incorrect "Raspberry Pi Zero 2 Wifi" nomenclature.

**Comment by vipulgupta2048** [comment]
Thanks @lurch for mentioning this 

> And whilst clicking around I also noticed that https://www.balena.io/os/docs/supported-boards/ incorrectly capitalises "[Raspberry Pi Zero](https://www.raspberrypi.com/products/raspberry-pi-zero/)" as "Raspberry Pi ZERO"; and that page also doesn't list the ARMv8 architecture used by [Raspberry Pi 4 Model B](https://www.raspberrypi.com/products/raspberry-pi-4-model-b/) ?

That page is on its way to deprecation. I would love to delete it just now, this is the modern page where we will redirect to https://www.balena.io/docs/reference/hardware/devices

Regarding nomenclature issues of RPi0 2 W, I will amend our device type contracts and that should propagate the name fix everywhere: https://github.com/balena-io/contracts/blob/597a3b1cd9c9abb5c11a137c4047a3da92b2d3ce/contracts/hw.device-type/raspberrypi0-2w-64/contract.json#L6

**Comment by vipulgupta2048** [comment]
PR here: https://github.com/balena-io/contracts/pull/284

**Comment by lurch** [comment]
Thanks :heart_eyes:
