### ISSUE TITLE
Review getting started guide

### ISSUE THREAD

**Issue by chrisys** [balena-io/docs#2060]
The getting started guide in the docs should be the golden path to get up and running with developing using a device on balenaCloud. We have other getting started guides but this one is specifically a guide to getting up and running with development.

Things to consider and approaches to take:
- [x] Create one definitive path from start to finish
- [x] Avoid distractions - the path should be clear without forks requiring the person following to make a decision they aren't yet informed enough to make
- [ ] #2621
- [x] Remove any 'advanced' usage notes or sections and move them to the appropriate place elsewhere in the docs
- [x] Remove typescript option for hello world app
- [x] Remove download OS config file description
- [x] Shorten paragraphs whilst retaining important information
- [x] Consider moving 'note' sections out of the flow and off to the side in another column
- [x] Use consistent naming for example fleets e.g. 'Your-Fleet'
- [x] Ensure the user knows to select and flash development mode image (see also: https://github.com/balena-io/balena-ui/issues/5044)
- [x] By the end of the guide the user should have a fleet, a device, an initial release, have pushed an update and know how to develop in local mode. They should be developing (i.e. editing source code and pushing changes) and know how to continue from here on their own.
- [x] At the end of the guide give a clear path to continue, don't just give a load of options
- [x] Remove troubleshooting notes and put them out of the flow of the getting started guide somewhere else in the docs (if we don't have them already)

Reference: [Alex uses balena notes](https://docs.google.com/document/d/1H9LUbU_0BFRgIqwsCD992z7sf2GMCaaMpHtqLYiCBq8/edit#)

**Comment by vipulgupta2048** [comment]
Created an issue for items pending. Closing this as mostly covered by #2613
