### ISSUE TITLE
Troubleshooting page is missing things we mention in the getting started guide

### ISSUE THREAD

**Issue by chrisys** [balena-io/docs#2061]
If the troubleshooting page should be the centre for all things troubleshooting, it should be expanded to include things such as checking network requirements and correcting WiFi credentials (as we refer to in the getting started guide).

**Comment by vipulgupta2048** [comment]
The troubleshooting guide will be THE place to hold troubleshooting information for a device. Everything you need to troubleshoot should end up here.
