### ISSUE TITLE
Raspberry Pi documentation links need updating

### ISSUE THREAD

**Issue by lurch** [balena-io/docs#2118]
This repo has [several links](https://github.com/balena-io/docs/search?q=raspberrypi.org/documentation) to the "old" Raspberry Pi documentation URLs. Note that as a result of both https://www.raspberrypi.com/news/bring-on-the-documentation/ and https://www.raspberrypi.com/news/new-raspberry-pi-website/ that all the documentation URLs have changed. There _are_ redirects in place, but these are only at a "broad level" and so you _may_ want to update your links to more specific parts of the pages.

For example, you have a link to https://www.raspberrypi.org/documentation/hardware/computemodule/cm-emmc-flashing.md - this currently redirects to https://www.raspberrypi.com/documentation/computers/compute-module.html but the part of the page that you'll **actually** want to link to is https://www.raspberrypi.com/documentation/computers/compute-module.html#flashing-the-compute-module-emmc
Similarly, you have several links to https://www.raspberrypi.org/documentation/configuration/config-txt/README.md which currently redirects to https://www.raspberrypi.com/documentation/computers/configuration.html but https://www.raspberrypi.com/documentation/computers/config_txt.html would be a more accurate link.

Of course this is only an issue if you want to make your links more targeted - if you're happy with the "broad level" redirects then you obviously don't need to do anything.

**Comment by aallan** [comment]
> Of course this is only an issue if you want to make your links more targeted - if you're happy with the "broad level" redirects then you obviously don't need to do anything.

I don't see us killing off those redirects any time soon. But there is the risk that bitrot will eventually make them less relevant, or kill them off for us entirely. Once you're two or three levels of redirect in things can get weird.

**Comment by vipulgupta2048** [comment]
Thanks for bringing this to our notice @lurch @aallan Created a PR to get this resolved: https://github.com/balena-io/docs/pull/2143
