### ISSUE TITLE
Clarify persistent logging's max size behaviour 

### ISSUE THREAD

**Issue by tmigone** [balena-io/docs#2136]
Persistent logging has a max size of 32MB for logs before journald starts rotating them. We need to clarify this behaviour so users don't expect to have all history of logging saved to disk. Masterclass has some additional information about this: https://www.balena.io/docs/learn/more/masterclasses/device-debugging/#52-persistent-logs

**Comment by vipulgupta2048** [comment]
@tmigone I recently started a PR to add a page about device logging, check it out to see if this resolves your issue.
