### ISSUE TITLE
Add Seeed Odyssey-x86 to Getting Started Guides

### ISSUE THREAD

**Issue by the-real-kenna** [balena-io/docs#2182]
[Seeed](https://www.seeedstudio.com/) has created support for their [ODYSSEY X86](https://www.seeedstudio.com/ODYSSEY-X86J4125864-p-4916.html) and it would be helpful to our joint customers to have it added to the list of balena Getting Started guides.

Seeed Logo: https://github.com/balena-os/balena-seeed-x86/blob/master/odyssey-x86.svg
Images of Hardware: https://www.seeedstudio.com/ODYSSEY-X86J4125864-p-4916.html
Board contract: https://github.com/balena-io/contracts/tree/master/contracts/hw.device-type/odyssey-x86

---

## About this issue tracker

*Before creating a issue, check for duplicates. If there is another issue describing
the same bug or problem, please add comments to pre-existing issues or link them to add more context.*

While creating a new issue, always make sure to provide as much context as possible with an
expected solution or change that you would like to see in the documentation. This helps
contributors understand the issue and execute a better solution. 

If applicable, please add additional links to GitHub projects, forums.balena.io threads,
gist.github.com, Google Drive attachments, screenshots, JF/FD/Front threads for reference, etc.

*Thank you for creating an issue and helping us improve balenaCloud's documentation!*

**Comment by the-real-kenna** [comment]
@vipulgupta2048 thanks for checking in again. The device got held here for longer than intended, and now needs to come to me for some troubleshooting. So the bad news is Alan hasn't received it to test your instructions yet. The good news is that I'll have it soon instead so that I can test them and give you feedback, hopefully by next week.

**Comment by vipulgupta2048** [comment]
Thanks for the update, Kenna!
