### ISSUE TITLE
Create a GH action to pin and manage externals

### ISSUE THREAD

**Issue by klutchell** [balena-io/docs#2201]
FD discussion (restricted access): https://www.flowdock.com/app/rulemotion/i-docs/threads/uUg_dan9e0xokAKronLSnWkQFV8

Example GH workflow:

1. on a weekly schedule
2. checkout docs source (checkout/v2)
3. run fetch-externals
4. commit and PR any changes (as the github-actions user I assume?)

I already know how to do steps 1-3 in an action, and I'm pretty sure 4 isn't that difficult or has actions available to make it easy. After all, link-checker can open issues, why shouldn't fetch-externals open PRs?

pros:

- only requires a scheduled GH action on docs repo, not anywhere else
- we choose the frequency of the schedule and the PR formatting
- commit hooks and deploy hooks no longer run fetch-externals
- externals are maintained in source control and can be rolled back easily

cons:

- created PRs will remain open forever unless we merge/close them (same as link-checker issues)
- only users subscribed to docs repo will be notified of changes to externals

**Comment by vipulgupta2048** [comment]
Resolved with daily deploys to CF. Closing.
