### ISSUE TITLE
Need Docs for Blocks

### ISSUE THREAD

**Issue by myarmolinsky** [balena-io/docs#2210]
We need Docs for Blocks, which means either genericizing or creating parallels for fleet headings in each of the below sections:
- Grant support access for a fleet
- Transfer fleet ownership
- Member types

We also need to create a section in the docs for *both* fleets and blocks about:
- Repository URLs and Fleet/Block Visibility

Aside from those, we need docs on creating Blocks and putting them to use in fleets. These should go in the `Develop` section of the docs

FD: https://www.flowdock.com/app/rulemotion/r-product/threads/4SFP0NE_EuLcJ5dFMhvi-eV0Yre
HQ: https://drive.google.com/file/d/1p86CewaRKBcKSd4g6HWpKma2Nk4I3QOO/view

**Comment by vipulgupta2048** [comment]
Release pinning --> Release management for block
Grant support access for a fleet --> Block support access 
Transfer fleet ownership --> Coming up
Member types --> Not doing it
Repository URLs and Fleet/Block Visibility --> Core block docs
