### ISSUE TITLE
Packet.com no longer exists

### ISSUE THREAD

**Issue by rhampt** [balena-io/docs#2221]
The Arm builder Packet.com reference in https://github.com/balena-io/docs/blob/master/pages/learn/welcome/security.md redirects. Has the location of our ARM builders changed?

**Comment by klutchell** [comment]
Packet renamed to Equinix Metal some time ago
https://metal.equinix.com/

**Comment by rhampt** [comment]
Thanks @klutchell I'll update the builder info then in the page

**Comment by vipulgupta2048** [comment]
Linking: https://github.com/balena-io/docs/pull/2222
