### ISSUE TITLE
Fleet membership management page is outdated.

### ISSUE THREAD

**Issue by cmfcruz** [balena-io/docs#2262]
A user has pointed out that our docs for fleet membership is outdated.  The page being described is here: https://www.balena.io/docs/learn/manage/account/#fleet-members

Here are some notable items about this page:
- Some screenshots and text still refer to fleets as apps.  The UI in the screenshot is also outdated.
<img width="229" alt="image" src="https://user-images.githubusercontent.com/23559242/165266529-0fabc39d-c920-41b8-9d01-2e8184812f43.png">
<img width="288" alt="image" src="https://user-images.githubusercontent.com/23559242/165266594-28504c6b-5bda-4a22-b922-ca2bd8818455.png">
- It does not mention that adding a user to an organization only allows 2 options for the roles: `Administrator` & `Member`
- It does not mention that as of the latest version of balenaCloud, new organization members do not have access to any block or fleet.
- It does not mention that the `Developer`, `Operator`, and `Observer` roles can only be set on the fleet membership of a user.

---

## About this issue tracker

*Before creating a issue, check for duplicates. If there is another issue describing
the same bug or problem, please add comments to pre-existing issues or link them to add more context.*

While creating a new issue, always make sure to provide as much context as possible with an
expected solution or change that you would like to see in the documentation. This helps
contributors understand the issue and execute a better solution. 

If applicable, please add additional links to GitHub projects, forums.balena.io threads,
gist.github.com, Google Drive attachments, screenshots, JF/FD/Front threads for reference, etc.

*Thank you for creating an issue and helping us improve balenaCloud's documentation!*

**Comment by vipulgupta2048** [comment]
> It does not mention that adding a user to an organization only allows 2 options for the roles: `Administrator` & `Member`

It doesn't because that page you referenced @cmfcruz is only for fleet management. Organization management is present here: https://www.balena.io/docs/learn/manage/organizations/#inviting-members-to-an-organization

>  It does not mention that the `Developer`, `Operator`, and `Observer` roles can only be set on the fleet membership of a user.

If we are explicit about that detail on the fleet management (Account docs), then would it help?

I consider the account's page as fleet management 
And, org management as org management. Maybe we can mention our distinction more explicitly to help clear the confusion. Let me know

**Comment by cmfcruz** [comment]
The docs already clearly state where the these roles apply.  We can already close this issue.
