### ISSUE TITLE
Amend docs to mention Customer Board Support instead of Custom Device Support

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-io/docs#2291]
This page https://www.balena.io/docs/reference/OS/custom-device-support/ mentions Custom Device Support (CDS) or at least goes back and forth about it. These docs specifically are for Customer Board Support (CBS)

CBS and CDS are 2 different processes. 

CBS is for customers that want to do their own board bring-up. 
CDS is a service that we offer to customers where we do the board bring up for them.

We need to amend this.

Context: https://www.flowdock.com/app/rulemotion/i-docs/threads/Ab3qdFisLJYSiktJq22XUyNJdyT

**Comment by rosswesleyporter** [comment]
Might be helpful to have an introduction that briefly describes the three options for using a device with balenaCloud:

Each device on balenaCloud must run balenaOS. There are three options for getting balenaOS supported on your device:

- [Existing Official Device Type](https://www.balena.io/docs/reference/hardware/devices/): Use one of the existing device types - this is what most customers do
- [Custom Device Support](https://www.balena.io/docs/reference/hardware/devices/) - As a service, Balena can add support for your specific device
- Customer Board Support - Customers are welcome to add support for their device, following the guide below

**Comment by vipulgupta2048** [comment]
Fixed with #2306
