### ISSUE TITLE
Getting Started guides CLI installer shows incorrect platform instructions

### ISSUE THREAD

**Issue by vipulgupta2048** [balena-io/docs#2297]
When you navigate to https://www.balena.io/docs/learn/getting-started/raspberrypi3/nodejs/#install-the-balena-cli using a Linux machine. 

The tab is selected for Linux but it's currently showing Mac instructions by default

![Screenshot from 2022-05-25 18-49-27](https://user-images.githubusercontent.com/22801822/170271602-86d2d2ba-5457-4b36-86da-6240c663d8a6.png)

**Comment by nucleardreamer** [comment]
@vipulgupta2048 what machine are you seeing that on, and also can you paste your user-agent string?

**Comment by vipulgupta2048** [comment]
@nucleardreamer Here you go https://whatismybrowser.com/w/K98S5KD
