### ISSUE TITLE
Wifi issue with BalenaOS 2.98.33 on intel-nuc devices

### ISSUE THREAD

**Issue by andrewivg** [balena-io/docs#2328]
--- sorry, I just realised I posted to the wrong repository, please delete this ---

**Comment by vipulgupta2048** [comment]
It happens to the best of us @andrewivg, just to be sure I think the issue is related to the Intel-nuc, but I don't see your issue on this repo: https://github.com/balena-os/balena-intel

Let me know if you found the right spot for it, happy to help
