### ISSUE TITLE
Device not released in production appear on the supported hardware list

### ISSUE THREAD

**Issue by alexgg** [balena-io/docs#2366]
When work starts on supporting a device type, a contract is added for it. As soon as that happens the device will appear both on `https://www.balena.io/docs/reference/hardware/devices/` and `balena devices supported`.

Probably there should be a further check to make sure that there is a also a hostapp with final releases on it before showing the device as supported.  

---

## About this issue tracker

*Before creating a issue, check for duplicates. If there is another issue describing
the same bug or problem, please add comments to pre-existing issues or link them to add more context.*

While creating a new issue, always make sure to provide as much context as possible with an
expected solution or change that you would like to see in the documentation. This helps
contributors understand the issue and execute a better solution. 

If applicable, please add additional links to GitHub projects, forums.balena.io threads,
gist.github.com, Google Drive attachments, screenshots, JF/FD/Front threads for reference, etc.

*Thank you for creating an issue and helping us improve balenaCloud's documentation!*

**Comment by vipulgupta2048** [comment]
Thanks for the suggestion @alexgg Is there a way for the API to provide that information to figure out if device contract is present but no balenaOS releases are present for it?

**Comment by alexgg** [comment]
hey @vipulgupta2048 I would image that an API call to list final releases for the hostapp fleet that is not empty would be enough.

**Comment by vipulgupta2048** [comment]
cc: @anujdeshpande @acostach This has been resolved. I can't see Radaxa Zero in the list anymore after Thodoris's fix.
