### ISSUE TITLE
Update recommended wireless adapters

### ISSUE THREAD

**Issue by alexgg** [balena-io/docs#2395]
The list of recommended wireless adapters in https://www.balena.io/docs/reference/hardware/wifi-dongles/ is outdated. This information should be generated from the OS documentation instead https://github.com/balena-os/meta-balena#recommended-wifi-usb-dongle  

---

## About this issue tracker

*Before creating a issue, check for duplicates. If there is another issue describing
the same bug or problem, please add comments to pre-existing issues or link them to add more context.*

While creating a new issue, always make sure to provide as much context as possible with an
expected solution or change that you would like to see in the documentation. This helps
contributors understand the issue and execute a better solution. 

If applicable, please add additional links to GitHub projects, forums.balena.io threads,
gist.github.com, Google Drive attachments, screenshots, JF/FD/Front threads for reference, etc.

*Thank you for creating an issue and helping us improve balenaCloud's documentation!*

**Comment by lurch** [comment]
This probably supersedes #2193 ?

**Comment by vipulgupta2048** [comment]
Not sure @lurch I am still waiting for folks concerned to update that PR. I will ping again
