### ISSUE TITLE
Google IoT shutting down

### ISSUE THREAD

**Issue by anujdeshpande** [balena-io/docs#2431]
Google cloud IoT is shutting down. We should remove any references to it - https://cloud.google.com/iot/docs/release-notes#August_16_2022

**Comment by vipulgupta2048** [comment]
Good one @anujdeshpande 
cc: @kb2ma can you confirm and if actionable then remove GCP IoT core object from here https://github.com/balena-io/docs/blob/master/config/dictionaries/cloud.json

**Comment by kb2ma** [comment]
Thanks for raising this issue. Posed a question internally on timing, and I'll come back here with the outcome.

**Comment by kb2ma** [comment]
Apologies for the delay, and thanks for the reminder @vipulgupta2048 . Working on a response.

**Comment by kb2ma** [comment]
Created #2463 deprecation notice, and archived the GitHub [gcp-iot-provision](https://github.com/balena-io-examples/gcp-iot-provision) repository.

**Comment by vipulgupta2048** [comment]
Thanks for your work on this before, during and after!
