### ISSUE TITLE
Users want to know how to invalidate their build cache

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#254]
An easy way to do this is to add 
`ENV VERSION=0.0.1`
to the dockerfile and increment as needed

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/L2luYm94ZXMvdG9waWNzLzI0Mzg5)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ith)

**Comment by vipulgupta2048** [comment]
Closing #331 via https://github.com/balena-io/docs/commit/e2e7c152460194e71838a246a69e4545ef4e3f0f
