### ISSUE TITLE
Add how to use basic virtual devices with resin

### ISSUE THREAD

**Issue by imrehg** [balena-io/docs#258]
Based on our [No hardware? Use VirtualBox to simulate a device for resin.io!](https://resin.io/blog/no-hardware-use-virtualbox/) blogpost.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24cn)

**Comment by sonyagreen** [comment]
Another request for this

**Comment by imrehg** [comment]
Now we have QEMU devices, should probably base the writeup on those.?

**Comment by zwalchuk** [comment]
covered by #650

**Comment by vipulgupta2048** [comment]
@shaunmulligan Should this be closed now? balenaOS in a container is experimental and till we have spawn in the CLI. I don't think there is any other way of creating virtual devices?

**Comment by shaunmulligan** [comment]
@vipulgupta2048 yeah i think that sounds okay and we can add something once we have balena spawn

**Comment by vipulgupta2048** [comment]
Roger that @shaunmulligan You will see some more notifications of me digging through old issues like this. Will keep the noise as low as possible, but would need your help.
