### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [balena-io/docs#2666]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by vipulgupta2048** [comment]
Thanks for reaching out. The process to responsibly disclose vulnerabilities regarding balena's products is to contact us at [security@balena.io](mailto:security@balena.io). The team will check into the issue and reproduce the issue if necessary. Let me know if you have more questions. Thanks!

Closing this.
