### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by kb2ma** [balena-io/docs#2686]
Image https://docs.balena.io/img/common/release-policy/devices_target_release_pencil.png does not display on page https://docs.balena.io/learn/deploy/release-strategy/release-policy/

Image does not display, only the outline rectangle. Clicking on the image location shows "Image failed to load" .

**Comment by vipulgupta2048** [comment]
@myarmolinsky The image you added recently is not working. Can you give it a look?
