### ISSUE TITLE
Need to document use of Bluetooth

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#276]
Users continually struggle with this. We need to correctly document it, especially for the RPI3 and point to known working example projects.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_jwl)

**Comment by josephroberts** [comment]
See https://github.com/resin-io-projects/rpi3-bluetooth

Not sure where the best place to talk about this is so I will leave it to @shaunmulligan and @imrehg 

My feeling is the whole "accessing hardware and peripherals" and "advanced boot configuration guide" needs a bit of a re-think to combine.

**Comment by shaunmulligan** [comment]
yeah, the plan has always been to do the "acccessing hardware" bit the same as we do for the getting started

**Comment by curcuz** [comment]
you need the following packages `bluez bluez-firmware` installed and then in your start-script you attach and bring up the interface:

```
# Attaching hci0 - sometimes the first attempt times out, so we make sure we a second attempt is performed
if ! /usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -; then
    echo "First try failed. Let's try another time."
    /usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
fi

# Bring hci0 up
hciconfig hci0 up
```

**Comment by vipulgupta2048** [comment]
@curcuz I think this can be added to troubleshooting - https://www.balena.io/docs/faq/troubleshooting/troubleshooting/#raspberry-pi

**Comment by curcuz** [comment]
@@vipulgupta2048 I'm not sure the above is still necessary.

**Comment by vipulgupta2048** [comment]
While dealing with issues this old, I am realizing soon enough that most things have long changed or became unnecessary 
@curcuz If it isn't needed any longer then please do longer the issue

**Comment by curcuz** [comment]
@vipulgupta2048 I think we now enable bluetooth by default but I can't say for sure so either testing or asking the OS folks is necessary - also I am not the owner of this issue

**Comment by vipulgupta2048** [comment]
Will do the digging and update this, thanks @curcuz

**Comment by vipulgupta2048** [comment]
Bluetooth has been enabled by default
