### ISSUE TITLE
Need to document Collaborators feature

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#281]
We currently don't have public facing docs on how collaborators feature works and some of the caveats and warts.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_jx2)

**Comment by sonyagreen** [comment]
Would be super handy for explaining collaboration best practices: https://github.com/resin-io/docs/commit/615f3d7f64168ff8c08d330c7cfe2c11dd7b3628

**Comment by zwalchuk** [comment]
Some documentation here: https://docs.resin.io/management/applications/#collaboration-management, but needs improvement.

**Comment by alisondavis17** [comment]
I was reminded of this again today, by a survey response asking for multiple users at the free level (basically, collaborators). Would be great to get this properly documented quickly. Will attach the Front ticket below.

**Comment by garethtdavies** [comment]
This issue is very dated. I'm closing as I believe this is covered by the explanations of member types https://www.balena.io/docs/learn/manage/account/#application-members.
