### ISSUE TITLE
All links on https://docs.balena.io/learn/more/glossary/ are incorrect.

### ISSUE THREAD

**Issue by dv-parkingspotz** [balena-io/docs#2831]
As per the title, all the links on the page https://docs.balena.io/learn/more/glossary/ are incorrect, one of them just redirects to the balena homepage and the other two 404.

**Comment by lurch** [comment]
The https://github.com/balenaltd/handbook/issues/new link 404s, but https://github.com/balenaltd/handbook says "This repository has been archived by the owner on Aug 11, 2023. It is now read-only." so that maybe explains why https://handbook.balena.io/ doesn't work any more? :man_shrugging:
