### ISSUE TITLE
Document how config.txt additions are applied and the device behaviour

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#296]
We need to detail the mechanism for how the supervisor applies changes to the config.txt file.

we also need to mention the current caveats and limitations.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_kii)

**Comment by shaunmulligan** [comment]
also need to mention that changing or adding to /boot in the container will have no affect on the device.

**Comment by vipulgupta2048** [comment]
Closing #296 via #1378
