### ISSUE TITLE
base-images.md broken links

### ISSUE THREAD

**Issue by cgsmith** [balena-io/docs#2969]
There are broken links that exist on https://github.com/balena-io/docs/blob/master/pages/reference/base-images/base-images.md

Check under the `#image-tags` section

**Comment by vipulgupta2048** [comment]
Thanks for reporting it in @cgsmith We are currently working on automating these pages of docs are pulling in accurate information directly from our base images build pipelines and populating the entire base images docs using that. Till that happens in the future, I have updated the 404 links with better locations that folks can visit in the future and they ideally won't 404
