### ISSUE TITLE
@oliverdunk Thanks for this! 👍 Its a huge improvement.

### ISSUE THREAD

**Issue by tersar33** [balena-io/docs#3006]
@oliverdunk Thanks for this! 👍 Its a huge improvement.

Just one quick request on the readme and it's ready to go

_Originally posted by @AmySteam in https://github.com/GoogleChrome/chrome-extensions-samples/pull/825#pullrequestreview-1283285154_

**Comment by vipulgupta2048** [comment]
Not sure if this was the right place to open the reference issue. 
Closing this atm, do clarify if this is not the case.
