### ISSUE TITLE
document autorestart policy

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#301]
based on https://docs.docker.com/engine/reference/run/#restart-policies-restart

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_raa)

**Comment by vipulgupta2048** [comment]
@shaunmulligan This could be the right place https://www.balena.io/docs/learn/develop/multicontainer/#docker-composeyml-file or am I looking in the wrong place?

**Comment by shaunmulligan** [comment]
yeah @vipulgupta2048 that looks like a good place to add it
