### ISSUE TITLE
UART usage on Artik5 & 10

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#305]
We need examples and info on UART usage for these boards.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_l3a)

**Comment by alisondavis17** [comment]
The ARTIK devices have been deprecated by Samsung and we no longer officially support them, so we can close this issue.
