### ISSUE TITLE
Improve getting started with windows

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#313]
Windows users seem to get confused by all the git a terminal stuff, we need a more windows focused section for these guys.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lfh)

**Comment by imrehg** [comment]
Yeah, came up quite a few times. That's a tough, but important one. Probably one of the first things is finding a good git client to use on Windows. (Eg. GitHub Desktop does not have great ux for git remotes, while almost every new user uses that...)

In addition to adding more Windows documentation, using cloud IDEs might help alleviate some of the issues, just a thought.

**Comment by garethtdavies** [comment]
Closing this due to git->CLI workflow changes.
