### ISSUE TITLE
Customizing device hostname

### ISSUE THREAD

**Issue by imrehg** [balena-io/docs#319]
How people can change their auto-generated device hostname. Possibly also add docs on how the hostnames are generated for the devices at the moment?

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lpo)

**Comment by zwalchuk** [comment]
Documented here: https://docs.resin.io/understanding/understanding-devices/2.0.0/#dev-vs-prod-images, but probably belongs somewhere else

**Comment by wcatron** [comment]
All these solution have to manually run on the host os or in a container. Is there a configuration variable that could be set per application or device? That seems like the simplest solution.

**Comment by vipulgupta2048** [comment]
Changing hostname through config.json and some information about hostnames are generated
https://www.balena.io/docs/reference/OS/overview/2.x/#development-vs-production-images
https://www.balena.io/docs/reference/OS/configuration/#sample-configjson

Changing Hostname through supervisor API
https://www.balena.io/docs/reference/supervisor/supervisor-api/#patch-v1devicehost-config

If there is a need to add the information above in a better place, then I think `FAQ` could be a good spot. Closing.
