### ISSUE TITLE
Document adding custom dtoverlays

### ISSUE THREAD

**Issue by imrehg** [balena-io/docs#320]
Users might want to add their custom device tree overlays on RPi. Document how to do that (compiling from source, enabling from the dashboard, etc).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lpq)

**Comment by garethtdavies** [comment]
Closing this as was added here: https://www.balena.io/docs/reference/OS/advanced/#setting-device-tree-overlays-dtoverlay-and-parameters-dtparam
