### ISSUE TITLE
Document How to trigger new pulls of git, etc during builds

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#330]
Users dont know about using ENV variable to pull a specific commit from git, or bump to a new version, etc

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_mul)

**Comment by vipulgupta2048** [comment]
@shaunmulligan I think this should be safe to close considering `git push balena master` is now considered ephemeral?
