### ISSUE TITLE
Document resin-nocache branch to clear builder cache

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#331]
git push resin master:resin-nocache

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_w43)

**Comment by zwalchuk** [comment]
@shaunmulligan does this have a different effect from using ENV VERSION=0.0.1 (as in #254), or is this a feature that eliminated the need for that?

**Comment by shaunmulligan** [comment]
@zwalchuk the branch was built to eliminate the need for that, but its still a neat thing to have for some usecases but not really needed for cache busting anymore

**Comment by xginn8** [comment]
This has since been documented in e2e7c152
