### ISSUE TITLE
Document weirdness around Go and non-MMX CPUs

### ISSUE THREAD

**Issue by petrosagg** [balena-io/docs#344]
Golang in general won't work on non-MMX CPUs because is uses MMX instructions to implement 64bit atomic operations.

For now, only our base images will carry a patch that allows one to use go on these platforms but only go 1.6.x and 1.7.x will work. 1.5.4 has further issues that we haven't fixed.

**Comment by garethtdavies** [comment]
I'm going to guess this is no longer relevant given we are several Golang versions past this and also likely referencing legacy base image?

**Comment by petrosagg** [comment]
I think that's right. Trong can answer this with certainty

**Comment by garethtdavies** [comment]
cc @nghiant2710 can you confirm this please?

**Comment by lurch** [comment]
Just out of curiosity, are there any platforms currently supported by BalenaOS which _don't_ have the required MMX instructions? :thinking:

**Comment by nghiant2710** [comment]
@lurch @garethtdavies, we did support one or two devices with Intel Quark SoC which does not have MMX instruction set however they are no longer supported atm so now I think we don't need to mention this in the docs.
