### ISSUE TITLE
"SIGN UP | LOGIN" on docs page is potentially confusing

### ISSUE THREAD

**Issue by lurch** [balena-io/docs#381]
When I login to the dashboard at https://dashboard.resin.io , there's a couple of links in the header "GETTING STARTED" and "DOCS" which link to the docs-site https://docs.resin.io .

In the top-right of the docs-site there's a button which says "SIGN UP | LOGIN" (each of which is a link back to the dashboard). This is slightly confusing, as I *am* logged in to the dashboard, but going to the docs-site makes it look like I've been logged out! It would be nice if the "SIGN UP | LOGIN" buttons weren't displayed if I'm currently logged in.

Feel free to close this issue if cross-domain browser security policies mean this isn't easily fixable.

**Comment by emirotin** [comment]
We don't use cookies (which can work from parent to children domains but have specific security vulnerabilities) and use local storage instead which is domain-specific. So I think it's indeed not possible to detect if the user is logged in from other domains.

We could change the text though to something like "Go to dashboard".

**Comment by lurch** [comment]
I've just double-checked, and if I login at https://dashboard.balena-cloud.com/ (using GitHub) then I can click on the "docs" link which takes me to https://balena.io/docs and the "SIGN UP | LOGIN" button still appears at the top-right, even though I *am* already logged in. (And if I click on "LOGIN" it takes me straight back to my list of apps)
So the issue as originally described still exists. Is it being closed as "won't fix" or "can't be bothered to fix" ? :wink:
