### ISSUE TITLE
Docs don't have info for the v2 (or newer) API

### ISSUE THREAD

**Issue by brownjohnf** [balena-io/docs#411]
@Page- It appears that the v2 API is released, but not documented. We really need to update the docs for it. Am I missing something somewhere?

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1h0r)

**Comment by pimterry** [comment]
@flesler @Page- @zwalchuk a user in gitter has just pointed this out too, and v1 is now _really_ old, we're on v3 about to release v4. How do we get these docs updated?

Do we have a plan for how we're going to manage showing docs for the multiple versions available? Worst case we can get by just showing the newest, imo, but medium-term a versioned docs solution would be nice.

**Comment by flesler** [comment]
This is something I haven't gotten into but would like learn how to so I can manage it. @Page- please ping if you whenever we could/should update the docs

**Comment by pimterry** [comment]
@flesler @Page- another user has just pointed this out in support, it'd be good to get this updated.

**Comment by lurch** [comment]
Fixed by #798 ?

**Comment by shaunmulligan** [comment]
The API docs now cover versions v1,v2,v3 and v4

**Comment by garethtdavies** [comment]
Closing this as up to date with v5 with this PR https://github.com/balena-io/docs/pull/1232
