### ISSUE TITLE
Discover base image tags from Docker Store

### ISSUE THREAD

**Issue by imrehg** [balena-io/docs#433]
Update documentation to point to Docker Store, instead of Docker Hub as the source of information for available tags for our base images, as the Docker Hub limits the amount of tags to be displayed, and we generate each day more image than that limit (by the look of it), so some tags are never shown.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_15pr)

**Comment by garethtdavies** [comment]
Closing this old issue as Docker Store is now part of Docker Hub and so no longer relevant. https://www.docker.com/blog/the-new-docker-hub/
