### ISSUE TITLE
Getting started with Rust and RPi 1 is not syncing via resin-cli

### ISSUE THREAD

**Issue by afitzek** [balena-io/docs#435]
In the rust tutorial the resin-cli sync is not working, because the target folder where the executable is constructed is included in the .gitignore file of the demo application. Resin-cli also ignores files in the .gitignore file and therefore is not syncing the actual new application to the device. Either the docs are updated to make use of the --skip-gitignore flag of resin-cli or the demo application needs to be adapted.

**Comment by zwalchuk** [comment]
Getting started guides no longer have resin sync instructions, so need to figure out if this still applies

**Comment by vipulgupta2048** [comment]
balena-cli doesn't have a sync command anymore and looks for .dockerignore file instead.
