### ISSUE TITLE
Explicit instructions for custom dns

### ISSUE THREAD

**Issue by hobochild** [balena-io/docs#440]
There are some network instructions https://docs.resin.io/deployment/network/ but could be more explicit. 

https://app2.frontapp.com/inboxes/shared/intercom/unassigned/242172547

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_17of)

**Comment by vipulgupta2048** [comment]
One can define custom DNS settings following this https://www.balena.io/docs/reference/OS/network/2.x/#network-requirements
