### ISSUE TITLE
User wants to know if they can use custom images

### ISSUE THREAD

**Issue by sonyagreen** [balena-io/docs#454]
Not clear in https://docs.resin.io/runtime/resin-base-images/

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1c7x)

**Comment by alisondavis17** [comment]
And the reverse: user wants to know if they are required to use a resin.io base image

**Comment by nghiant2710** [comment]
This one can be closed as everything is now in our current base images docs https://www.balena.io/docs/reference/base-images/base-images/#balena-base-images
