### ISSUE TITLE
Document use of RPI compute modules

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#461]

**Comment by lurch** [comment]
Presumably this also has overlaps with Project Fin ?

**Comment by vipulgupta2048** [comment]
Hey @lurch @Bucknalla Any context on use of the RPI compute modules in what way? AFAIK The only way one can use compute modules is through the Fin being used as a carrier board. In the context of balena, that's the only one (balena Fin) we support right?

**Comment by Bucknalla** [comment]
@vipulgupta2048 not sure what we'd want to document here? The compute module isn't really useful on its own so needs a carrier board to provide it with power, peripherals, etc. Typically we'd document to the compute module carrier board in this context so the balenaFin.

**Comment by vipulgupta2048** [comment]
Sounds right to me. Thanks for the assist, folks! Another issue down for the count.
