### ISSUE TITLE
Need clear documentation about avahi availability in resinOS 1.x

### ISSUE THREAD

**Issue by brownjohnf** [balena-io/docs#465]
We had a support issue where a user thought that avahi would be available in 1.x based on https://resinos.io/docs/architecture/#resin-device-toolbox for resinOS 2.x devices. We should mention that it's 2.x only in there.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1f09)

**Comment by shaunmulligan** [comment]
Only ~1.5% of the fleet is on 1.x these days, so i think this issue can just be closed.
