### ISSUE TITLE
Add documentation for Preloaded images

### ISSUE THREAD

**Issue by lifeeth** [balena-io/docs#480]
This is currently just a blog post at - https://resin.io/blog/preloaded-containers/

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1g4r)

**Comment by imrehg** [comment]
Also https://resin.io/blog/advanced-device-provisioning-workflow-for-large-fleets-preloading-and-pre-provisioning/

And yes, have to turn into docs.

**Comment by zwalchuk** [comment]
We'll add this to our "Going to production" docs after we do a couple more blogs that are similar. I'll take over ownership

**Comment by vipulgupta2048** [comment]
Documentation available for `balena preload` - https://www.balena.io/docs/reference/balena-cli/#preload-image
Masterclass reference for preloading images - https://www.balena.io/docs/learn/more/masterclasses/advanced-cli/#5-preloading-and-preregistering
Going to production - https://www.balena.io/docs/learn/welcome/production-plan/#preloading-images-and-preregistering-devices
