### ISSUE TITLE
How to use hostOS avahi from Dbus

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#486]
example: https://github.com/resin-io-playground/resin-avahi-dbus

relevant forum thread: https://forums.resin.io/t/advertising-container-hostname-using-avahi-daemon-in-resinos-v2/728

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1ifz)

**Comment by ab77** [comment]
https://github.com/balena-io/balenaos-masterclass/pull/12

**Comment by vipulgupta2048** [comment]
Closing in favor of https://github.com/balena-io/balenaos-masterclass/pull/12
