### ISSUE TITLE
Document what resinOS_uEnv.txt is and what is for

### ISSUE THREAD

**Issue by jviotti** [balena-io/docs#510]
This file came up in a support question, but we don't have any documentation about it.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_578x)

**Comment by jhermsmeier** [comment]
@zwalchuk why has this been closed as "wontfix"? Just general cleanup, or are there other reasons? Asking because this just came up again in connection with enabling UART5 on Beaglebone Blacks.

**Comment by zwalchuk** [comment]
@jhermsmeier I was cleaning up, but can definitely reopen. Can you link the front thread to it for context?

**Comment by jhermsmeier** [comment]
Ah, okay, cheers! Front is currently bugged around letting me add issues, so here's the convo for now: https://app.frontapp.com/open/cnv_e5ttgx

**Comment by jviotti** [comment]
Closing stale issues
