### ISSUE TITLE
User wants to know NPM version

### ISSUE THREAD

**Issue by sonyagreen** [balena-io/docs#524]
In the case where a user is installing npm and nodejs separately, we could specify this in our documentation.

https://resin.io/blog/advanced-device-provisioning-workflow-for-large-fleets-preloading-and-pre-provisioning/ and https://github.com/resin-io/resin-cli.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1unr)

**Comment by vipulgupta2048** [comment]
@pdcastro Ancient issue here, just confirming that if we do warn/notify users when they try to install the CLI in old or very new versions of Node/NPM right?

**Comment by vipulgupta2048** [comment]
If yes, we can close this one.

**Comment by pdcastro** [comment]
Yes, I think we can close this issue. It predates the [current CLI installation instructions](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md) that specify the Node.js version requirements, and I think it also predates the availability of the alternative, recommended installation options: GUI installers and standalone zip packages that bundle Node.js in them.
