### ISSUE TITLE
Links in getting started guide should open in new tab

### ISSUE THREAD

**Issue by alisondavis17** [balena-io/docs#525]
Currently, links in the getting started guide open in the same tab, but links should open in new tabs so the user can keep the getting started guide open. 

Examples of links that open in same tab but should open in a new tab: 

<img width="714" alt="screen shot 2017-06-09 at 10 15 56 pm" src="https://user-images.githubusercontent.com/20308284/27000214-4c40d4ca-4d61-11e7-97b0-918d6e5c96a1.png">

**Comment by zwalchuk** [comment]
@craig-mulligan not sure where to fix this, I'm happy to fix if you show me where

**Comment by craig-mulligan** [comment]
@zwalchuk, so we can either add the links as html for example `<a href="url" target="_blank">my link</a>`  or we could add some special markdown syntax for custom attributes. 

I'd vote for the custom syntax as it'll keep things readable. To do that we need to expose the markdown renderer from the underlying `doxx` library, which should be possible right @emirotin?

**Comment by poshrolls** [comment]
Topic for ProductOS / BalenaOS call - bigger issue for all docs.

**Comment by vipulgupta2048** [comment]
Closing this in favor of #2621
