### ISSUE TITLE
Nav overflow hides search on some screen widths.

### ISSUE THREAD

**Issue by hobochild** [balena-io/docs#565]
On small screen width the fixed nav overflows and blocks the search box. Reported by @josephroberts 

<img width="1002" alt="screen shot 2017-08-15 at 12 37 38" src="https://user-images.githubusercontent.com/9499917/29314652-cfa34a6c-81b6-11e7-8460-3c10215e2ad3.png">

**Comment by garethtdavies** [comment]
This is an old issue but I tested this on a set of modern browsers and no longer seems to be an issue. Please reopen this if the issue persists.
