### ISSUE TITLE
Better explain exactly what happens to a container during "Restart Application"

### ISSUE THREAD

**Issue by zwalchuk** [balena-io/docs#587]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ce7)

**Comment by srlowe** [comment]
I started taking a look at this.  It seems to me that it's already documented well.  The front link is also broken so we don't have any context.

https://www.balena.io/docs/learn/manage/actions/#restart-application****
