### ISSUE TITLE
User wants to learn about persistent logging

### ISSUE THREAD

**Issue by sonyagreen** [balena-io/docs#597]
When a user wants to learn about persistent logging:
1. There's one doc, which gives basic info, but doesn't explain what is logged
2. Searching [logging](https://docs.resin.io/search-results?searchTerm=logging) yields a bunch of results - the only answer to persistent logging is the second result
3. The first search result ([resinOS projects](https://docs.resin.io/examples/projects/)) doesn't have the word logging in it -- do we have fuzzy searching, and why would that top hit be at the top if it's matching on 'logger' when there's a direct hit?

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2k4p)

**Comment by imrehg** [comment]
Also now need to add that persistent logging is enabled in the dashboard on supervisors v7.15.0+.

**Comment by andrewnhem** [comment]
Adding to persistent logging definition here: https://github.com/balena-os/meta-balena/pull/2140

Will close once that merges and we test it docs-side.

**Comment by robertgzr** [comment]
@andrewnhem looks like that change made it to prod https://www.balena.io/docs/reference/OS/configuration/#persistentlogging

**Comment by dtischler** [comment]
We should expand our documentation to be a bit more verbose, we need to include a Warning that the device will be immediately rebooted upon Enabling Persistent Logging, and we should include a screenshot for visual guidance, as well.

**Comment by vipulgupta2048** [comment]
Should be solved with the new device logs page: #2148
