### ISSUE TITLE
Supervisor update-lock information needs more details

### ISSUE THREAD

**Issue by imrehg** [balena-io/docs#638]
The update locking mechanism needs more information as it is sparse and hard to find

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5o0x)

**Comment by imrehg** [comment]
Related: 

* https://github.com/resin-io/resin-supervisor/pull/528
* https://github.com/resin-io/docs/pull/639

**Comment by lekkas** [comment]
> Locking updates means that the Supervisor will not be able to kill your application. This is meant to be used at critical sections of your code where you don't want to be interrupted, or to control that updates are only installed at certain times.

One more things to add here (in what I see is a placeholder ticket for improved update lock documentation) , we should mention that update locks do not block the images from being downloaded to the device.

**Comment by shaunmulligan** [comment]
@imrehg do you think the update locking docs are sufficient these days?

**Comment by vipulgupta2048** [comment]
I think they are https://www.balena.io/docs/learn/deploy/release-strategy/update-locking/
