### ISSUE TITLE
Document limitations of logging

### ISSUE THREAD

**Issue by brownjohnf** [balena-io/docs#723]
We should make it clear in the docs that logs are not permanently persisted, and the specifics of how much persistence is provided. Maybe some examples about alternative logging solutions, as well.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_8cc9)

**Comment by alisondavis17** [comment]
Yes - and we actually just need to document logging in general, since I don't think we have any docs on it. 

Note that the persistence period will change from time-based to line-based when we release "logs 2.0" imminently.

**Comment by zwalchuk** [comment]
@alisondavis17 @brownjohnf Logs get their own page in the docs restructure, so I'll make sure it's populated with this info. Should have it up sometime next week
