### ISSUE TITLE
Update rust getting started instructions

### ISSUE THREAD

**Issue by zwalchuk** [balena-io/docs#739]
https://forums.resin.io/t/rustup-fails-for-armv8l/2661

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9r7l)

**Comment by vipulgupta2048** [comment]
Fixed that by uniforming all Getting Started examples
