### ISSUE TITLE
Emphasize that for production base images should be version-pinned

### ISSUE THREAD

**Issue by brownjohnf** [balena-io/docs#758]
I think we should make it clear in the docs that it's best practice to version-pin your base image, to ensure you don't accidentally pull in breaking changes.

At a minimum we should explain the concepts and the risks/benefits of pinning vs. not pinning.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_a2h7)

**Comment by garethtdavies** [comment]
This is covered in #1344

**Comment by vipulgupta2048** [comment]
Could be part of #1617

**Comment by vipulgupta2048** [comment]
Closing in favor of #1720
