### ISSUE TITLE
User wants more examples on device tags

### ISSUE THREAD

**Issue by lekkas** [balena-io/docs#775]
- Based on [user feedback](https://www.flowdock.com/app/rulemotion/sales/threads/04VnY746xVT_r-X9DCcrJ9FbAQk)

Note that we already have some examples by @thgreasi at https://github.com/resin-io-playground/device-tags

**Comment by vipulgupta2048** [comment]
Closing in favor off
Quite recently #1588 added more examples to API for device tags, 
CLI goes into detail about adding tags https://www.balena.io/docs/reference/balena-cli/#tag-set-tagkey-value
SDK - https://www.balena.io/docs/reference/sdk/node-sdk/#balena.models.application.tags.set

**Comment by thgreasi** [comment]
@vipulgupta2048 https://github.com/balena-io-examples/device-tags is still what I point customers to though.
Moreover it is now under the coinsidendentialy properly named balena-io-examples org :)
Maybe it is worth adding a mention somewhere in the docs as well if we already have page good to host it.
Perhaps a page about tags that has links to all our tag related resources :thinking:

**Comment by vipulgupta2048** [comment]
@thgreasi Already covering the balena-io-examples here. We will list them all on one page  #1608

**Comment by thgreasi** [comment]
that's great @vipulgupta2048 :+1:
