### ISSUE TITLE
Nested bulleted lists have strange spacing

### ISSUE THREAD

**Issue by zwalchuk** [balena-io/docs#797]
Seems to be related to the markdown rendering: https://docs.resin.io/reference/cli/

**Comment by vipulgupta2048** [comment]
![Uploading Screenshot from 2021-03-10 02-22-28.png…]()

**Comment by vipulgupta2048** [comment]
![Screenshot from 2021-03-10 02-22-28](https://user-images.githubusercontent.com/22801822/110536471-83dea600-8147-11eb-9c25-a57b08e1dde0.png)

**Comment by gantonayde** [comment]
Bullet points in [Choosing a shell](https://www.balena.io/docs/reference/balena-cli/#choosing-a-shell-command-promptterminal) do not follow the page pattern and sub-bullet points do not have an empty trailing line:

![bullets2](https://user-images.githubusercontent.com/64661854/111804679-f8001300-88d8-11eb-9eab-cf5371637d18.jpg)
