### ISSUE TITLE
Build failing: Missing or forbidden tags in commits, see `repository.yml`

### ISSUE THREAD

**Issue by chibby0ne** [balena-io/docs#828]
I submitted a few PRs (see #827 and #826) for some simple edits on the doc, but they failed with the error by Versionist:

```
Missing or forbidden tags in commits, see `repository.yml`
```
I've tried searching for this file in the repo to no avail.

Trying to get more details on the root cause of the issue is not possible since I don't have access to the CI details.

Can someone clarify why is the build failing so that I can make the appropriate changes?

**Comment by lurch** [comment]
IIRC you need to add a `Change-type: <major|minor|patch>` footer to the bottom of your commit message.

**Comment by zwalchuk** [comment]
@chibby0ne we also have some troubles with our CI system running tests for external contributors, so you may see some messages related to that. I will be taking your edits, however, and including them in a general update PR, so thank you very much for contributing!

**Comment by chibby0ne** [comment]
@zwalchuk I see. Would @lurch suggestion help in any case?

**Comment by zwalchuk** [comment]
@chibby0ne that's what would fix that particular error (and what we do internally), but because of our current process it doesn't matter because I need to create a new commit anyway. We're putting a new CI system in place though that might allow for a better process, I'll bring it up with the team

**Comment by chibby0ne** [comment]
@zwalchuk Ok so I'll just leave these PRs for you to squash and merge then. Can you let me know when the new CI is put in place and also it would be great if you could specify what the requirements for PRs will be with a `.github/CONTRIBUTING.md` for the new CI?

**Comment by vipulgupta2048** [comment]
Both PR's mentioned by the user has been merged
