### ISSUE TITLE
Check supported docker-compose fields

### ISSUE THREAD

**Issue by afitzek** [balena-io/docs#843]
There seems to be an inconsistency in our docs, with supported docker compose fields (https://docs.resin.io/reference/supervisor/docker-compose/#supported-fields). We should recheck them. For example we claim that cpus is supported, but cpus is only supported in version 2.2 and we do not support version 2.2.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ckzn)

**Comment by garethtdavies** [comment]
Related to https://github.com/balena-io/docs/pull/1369
