### ISSUE TITLE
Document how to set multiple dtoverlay values

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#882]
It is possible to use a comma separated list as so:

`RESIN_HOST_CONFIG_dtoverlay ` = `"balena-fin","rpi-sense"`

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dmuj)

**Comment by majorz** [comment]
Another instance of a user being unaware of how to define those as multiple values on [Front](https://app.frontapp.com/open/cnv_zxkbub).

**Comment by pcarranzav** [comment]
The docs should also make it clear that besides being comma-separated, each value has to be enclosed in quotes, as this will be parsed as the contents of a JSON array.
