### ISSUE TITLE
Note that RESIN_SUPERVISOR_API_KEY and RESIN_SUPERVISOR_ADDRESS are not enabled by default

### ISSUE THREAD

**Issue by jviotti** [balena-io/docs#884]
This says the opposite: https://docs.resin.io/learn/develop/runtime/#supervisor.

Check this thread: https://app.frontapp.com/inboxes/shared/30574/unassigned/2129589243

**Comment by shaunmulligan** [comment]
I believe this is already fixed since new supervisor docs were pulled in
