### ISSUE TITLE
Document the ability to change application name for non-legacy apps

### ISSUE THREAD

**Issue by dimitrisnl** [balena-io/docs#886]
https://github.com/resin-io/resin-api/pull/1330

Include 'app_name' as part of acceptable properties during a PATCH call in the Application resource

**Comment by shaunmulligan** [comment]
@dimitrisnl I assume this has been deployed now?

**Comment by dimitrisnl** [comment]
![Screen Shot 2019-04-12 at 9 50 16 AM](https://user-images.githubusercontent.com/4951004/56017675-b1770680-5d08-11e9-9f3d-e1732ae57937.png)

I see that the param is included there already now
