### ISSUE TITLE
Error in API docs to fetch all devices by application

### ISSUE THREAD

**Issue by pcarranzav** [balena-io/docs#900]
In https://docs.resin.io/reference/api/resources/device/

The request should be to `"https://api.resin.io/v4/application(<ID>)?\$expand=owns__device"` instead of `"https://api.resin.io/v4/application(<ID>)?\$expand=device"`

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_drsj)

**Comment by garethtdavies** [comment]
This was fixed so closing.
