### ISSUE TITLE
Navigation error when trying to view application's api

### ISSUE THREAD

**Issue by karaxuna** [balena-io/docs#934]
![bug](https://user-images.githubusercontent.com/2152815/47993219-65e08100-e108-11e8-821c-9e64fb0837f4.gif)

**Comment by chrisys** [comment]
This is fixed in https://github.com/balena-io/doxx/commit/1f7c804edd4e6f9ec9a3778b59eda3cdcba07a24 awaiting deploy

**Comment by chrisys** [comment]
Fixed and deployed in 570b437
