### ISSUE TITLE
Network requirements incorrectly list *.www.balena.io

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-io/docs#935]
https://www.balena.io/docs/reference/OS/network/2.x/#network-requirements

The network requirements documentation state that you should whitelist `*.www.balena.io` domains, but this should be `*.balena-cloud.com` I believe.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_f19v)

**Comment by chrisys** [comment]
Also present here https://www.balena.io/docs/faq/troubleshooting/faq/#what-network-ports-are-required-
