### ISSUE TITLE
Documentation mobile version has wrong links and images.

### ISSUE THREAD

**Issue by dansku** [balena-io/docs#952]

**Comment by dansku** [comment]
Mobile version of the page is missing /docs/ as url prefix.

**Comment by dimitrisnl** [comment]
@dansku 	I only see that the nav bar image is broken. Are there else I'm missing?

**Comment by dansku** [comment]
@dimitrisnl the nav bar is broken, and also all the menu links lack `/docs/` in the url.

**Comment by dimitrisnl** [comment]
@dansku 	Yeah, I only mentioned to images. I'm aware of the navigation issue.
It's pretty strange really. Both the desktop and mobile navigation use the same partial template. I believe this issue lies with `doxx` not properly applying the `docs` prefix.

Have to investigate some more.

**Comment by dimitrisnl** [comment]
I have identified the issue for the links. 
We parse all the anchor elements with Jquery and prefix them with `docs`.

Now the mobile navigation is not present in the DOM while we do the above operation but instead rendered afterward. Consequently, when the navigation links are rendered in the document, they are missing the docs prefix. Working on a fix.
