### ISSUE TITLE
Some getting started pages do not redirect properly

### ISSUE THREAD

**Issue by thgreasi** [balena-io/docs#958]
The following urls, as found in `/config`'s `gettingStartedLink` of the respective device types, do a bad redirect and end up with a "Page not found" error:

- http://docs.resin.io/#/pages/installing/gettingStarted-ODROID-C1.md#windows
- http://docs.resin.io/#/pages/installing/gettingStarted-ODROID-XU4.md#windows
- http://docs.resin.io/dart6ul/nodejs/getting-started/
- http://docs.resin.io/nuc/nodejs/getting-started/
- https://docs.resin.io/asus-tinker-board-s/nodejs/getting-started/
- https://docs.resin.io/asus-tinker-board/nodejs/getting-started/
- https://docs.resin.io/beaglebone/nodejs/getting-started/
- https://docs.resin.io/iot2000/nodejs/getting-started/
- https://docs.resin.io/raspberrypi/nodejs/getting-started/
- https://docs.resin.io/raspberrypi2/nodejs/getting-started/

**Comment by thgreasi** [comment]
The following seem that can be fixed with a few fixes in https://github.com/balena-io/docs/blob/master/config/redirects.txt
- http://docs.resin.io/imx6ul-var-dart/nodejs/getting-started/
- http://docs.resin.io/intel-nuc/nodejs/getting-started/
- https://docs.resin.io/beaglebone-black/nodejs/getting-started/
- https://docs.resin.io/raspberry-pi/nodejs/getting-started/
- https://docs.resin.io/raspberry-pi2/nodejs/getting-started/

Two of them seem to need special handling:
- http://docs.resin.io/#/pages/installing/gettingStarted-ODROID-C1.md
- http://docs.resin.io/#/pages/installing/gettingStarted-ODROID-XU4.md

On the other hand the following do not exist 
- https://docs.resin.io/asus-tinker-board-s/nodejs/getting-started/
- https://docs.resin.io/asus-tinker-board/nodejs/getting-started/
- https://docs.resin.io/iot2000/nodejs/getting-started/

**Comment by shaunmulligan** [comment]
closed by #959

**Comment by thgreasi** [comment]
@shaunmulligan I intentionally didn't close this since I couldn't fix the redirects for the following getting started links.

- http://docs.resin.io/#/pages/installing/gettingStarted-ODROID-C1.md
- http://docs.resin.io/#/pages/installing/gettingStarted-ODROID-XU4.md

**Comment by shaunmulligan** [comment]
@thgreasi ah sorry, didn't realise that. Yeah I think lets open a more specific issue for the odroid boards
