### ISSUE TITLE
Documentation advertises inexistent `--balenaio` build flag

### ISSUE THREAD

**Issue by agherzan** [balena-io/docs#965]
The [Custom Build Docs](https://www.balena.io/os/docs/custom-build/#supporting-your-own-board) advise you to specify the `--balenaio` flag in order to create a managed build. This uses to be the `--resinio` flag which was completely removed after OS unification work.

Initially reported here: https://github.com/balena-os/meta-balena/issues/1289

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fm3f)

**Comment by shaunmulligan** [comment]
For this we should probably just pull in the docs from meta-balena, so they stay in sync

**Comment by agherzan** [comment]
This is not documented in meta-resin as it is a tool the boards are importing as submodule: https://github.com/balena-os/balena-yocto-scripts.

**Comment by xginn8** [comment]
fixed in https://github.com/balena-io/resin-site/commit/05e992a16637aba51b59f8f7c2ad85073ed7341e
