### ISSUE TITLE
Odroid getting started pages do not redirect properly

### ISSUE THREAD

**Issue by thgreasi** [balena-io/docs#973]
The following urls, as found in /config's gettingStartedLink of the respective device types, do a bad redirect and end up with a "Page not found" error:

- http://docs.resin.io/#/pages/installing/gettingStarted-ODROID-C1.md#windows
- http://docs.resin.io/#/pages/installing/gettingStarted-ODROID-XU4.md#windows

See: #958

**Comment by xginn8** [comment]
I've just retested all ODROID-C1 & ODROID-XU4 getting started pages and all work as expected. Closing.
