### ISSUE TITLE
Indicate that RESIN_APP_RELEASE was deprecated in OS v2.12.x

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#985]
In the example `printenv` of https://www.balena.io/docs/learn/develop/runtime/ we show that this variable exists, we should remove it from there and indicate that it was removed in OS v2.12.7 and the recommended method of getting the app commit is to use the supervisor API

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fseb)

**Comment by xginn8** [comment]
this has already been cleaned up
