### ISSUE TITLE
Update and validate Azure integration

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#986]
I believe our integration with Azure is a bit out of date, we should check and update that.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fts3)

**Comment by kb2ma** [comment]
Azure integration was updated with the 3rd party integration update in #2329.
