### ISSUE TITLE
Improve docs search

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/docs#989]
Currently searching for some keywords don't return the correct results, some examples are:

- "kernel-modules" should at least highlight this page: https://www.balena.io/docs/learn/develop/multicontainer/#labels
- "RESIN_" this doesn't seem to show any very relevant pages

**Comment by garethtdavies** [comment]
Link to tips for improving results. that we can implement: https://community.algolia.com/docsearch/tips.html
And here is the DocSearch config file (which we can submit a PR against): https://github.com/algolia/docsearch-configs/blob/master/configs/balena.json

**Comment by Hades32** [comment]
Searching for "io.balena.features.firmware" also didn't return results although the docs do contain it. I guess non word characters are simply handled poorly

**Comment by vipulgupta2048** [comment]
Thanks @Hades32 for pinging on this issue. Would you like to take this issue up to solve it? We are doing a cleanup of issues on a volunteer basis. So resolving this finally will help quite a bit.

**Comment by Hades32** [comment]
I just realized we're using an external service for search. From looking at their docs I think we would need to create a issue, as the config doesn't seem to allow changing the handling of non-word characters.
Do we have a paid account with them?

**Comment by vipulgupta2048** [comment]
@Hades32 Doesn't seem like it, I was reading about it on the website. Their scraper handles the collection with the config that we have submitted above. Docsearch doesn't seem like a paid service so you can just open the issue and see if we get a response. Maybe we can also improve our balena.json file?
